"""domain separation

Revision ID: 49d94bae5339
Revises: 9a6429095aa2
Create Date: 2026-03-09 12:19:47.391392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49d94bae5339'
down_revision: Union[str, Sequence[str], None] = '9a6429095aa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_fx_configuration',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_product_id', sa.UUID(), nullable=False),
    sa.Column('supported_currencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fx_rate_source', sa.String(), nullable=True),
    sa.Column('fx_conversion_method', sa.String(), nullable=True),
    sa.Column('foreign_markup_fee_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cross_border_fee_applicable', sa.Boolean(), nullable=True),
    sa.Column('cross_border_fee_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['card_product_id'], ['card_product_core.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_product_id')
    )
    op.drop_table('credit_product_international_config')
    op.add_column('card_transaction_controls', sa.Column('pos_allowed', sa.Boolean(), nullable=True))
    op.add_column('card_transaction_controls', sa.Column('ecommerce_allowed', sa.Boolean(), nullable=True))
    op.add_column('card_transaction_controls', sa.Column('atm_withdrawal_allowed', sa.Boolean(), nullable=True))
    op.add_column('card_transaction_controls', sa.Column('international_txn_allowed', sa.Boolean(), nullable=True))
    op.add_column('card_transaction_controls', sa.Column('international_txn_limit_cap', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('card_transaction_controls', sa.Column('international_cash_allowed', sa.Boolean(), nullable=True))
    op.drop_column('card_transaction_controls', 'atm_enabled')
    op.drop_column('card_transaction_controls', 'pos_enabled')
    op.drop_column('card_transaction_controls', 'ecommerce_enabled')
    op.drop_column('card_usage_limits', 'international_txn_daily_cap')
    op.alter_column('credit_account', 'card_product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('credit_product_fees', 'foreign_markup_fee_pct')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_product_fees', sa.Column('foreign_markup_fee_pct', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.alter_column('credit_account', 'card_product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('card_usage_limits', sa.Column('international_txn_daily_cap', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('card_transaction_controls', sa.Column('ecommerce_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('card_transaction_controls', sa.Column('pos_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('card_transaction_controls', sa.Column('atm_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('card_transaction_controls', 'international_cash_allowed')
    op.drop_column('card_transaction_controls', 'international_txn_limit_cap')
    op.drop_column('card_transaction_controls', 'international_txn_allowed')
    op.drop_column('card_transaction_controls', 'atm_withdrawal_allowed')
    op.drop_column('card_transaction_controls', 'ecommerce_allowed')
    op.drop_column('card_transaction_controls', 'pos_allowed')
    op.create_table('credit_product_international_config',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('credit_product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('international_txn_allowed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('supported_currencies', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('fx_rate_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fx_conversion_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cross_border_fee_applicable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('cross_border_fee_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('international_cash_allowed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('international_txn_limit_cap', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['credit_product_id'], ['credit_product_information.id'], name=op.f('credit_product_international_config_credit_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('credit_product_international_config_pkey')),
    sa.UniqueConstraint('credit_product_id', name=op.f('credit_product_international_config_credit_product_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('card_fx_configuration')
    # ### end Alembic commands ###
