"""Fix credit product governance FKs to admins

Revision ID: 89f11f69a390
Revises: 1c2c2204432e
Create Date: 2026-03-03 12:19:47.065303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89f11f69a390'
down_revision: Union[str, Sequence[str], None] = '1c2c2204432e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('credit_product_governance_updated_by_fkey'), 'credit_product_governance', type_='foreignkey')
    op.drop_constraint(op.f('credit_product_governance_created_by_fkey'), 'credit_product_governance', type_='foreignkey')
    op.drop_constraint(op.f('credit_product_governance_approved_by_fkey'), 'credit_product_governance', type_='foreignkey')
    op.create_foreign_key(None, 'credit_product_governance', 'admins', ['approved_by'], ['id'])
    op.create_foreign_key(None, 'credit_product_governance', 'admins', ['created_by'], ['id'])
    op.create_foreign_key(None, 'credit_product_governance', 'admins', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'credit_product_governance', type_='foreignkey')
    op.drop_constraint(None, 'credit_product_governance', type_='foreignkey')
    op.drop_constraint(None, 'credit_product_governance', type_='foreignkey')
    op.create_foreign_key(op.f('credit_product_governance_approved_by_fkey'), 'credit_product_governance', 'users', ['approved_by'], ['id'])
    op.create_foreign_key(op.f('credit_product_governance_created_by_fkey'), 'credit_product_governance', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('credit_product_governance_updated_by_fkey'), 'credit_product_governance', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###
