"""Add pin_hashed to card

Revision ID: 923cf6777035
Revises: a29f7d3ffc7e
Create Date: 2026-03-12 11:38:50.334311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '923cf6777035'
down_revision: Union[str, Sequence[str], None] = 'a29f7d3ffc7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('pin_hashed', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'pin_hashed')
    # ### end Alembic commands ###
