print("Importing app.api.auth")
import app.api.auth
print("Importing app.api.customer")
import app.api.customer
print("Importing app.api.application")
import app.api.application
print("Importing app.admin.api.auth")
import app.admin.api.auth
print("Importing app.admin.api.credit_product")
import app.admin.api.credit_product
print("Importing app.admin.api.card_product")
import app.admin.api.card_product
print("Importing app.admin.api.issuance")
import app.admin.api.issuance
print("All done")
