"""Admin schemas for the ZBANQUe Credit Card System."""
from pydantic import BaseModel, EmailStr, Field, field_validator, ConfigDict
from uuid import UUID
from datetime import datetime
from typing import Optional

from app.core.roles import Role


class AdminFullName(BaseModel):
    """Structured name input for admin creation."""
    first_name: str = Field(..., min_length=2, description="Admin's first name")
    last_name: str = Field(..., min_length=2, description="Admin's last name")

    @field_validator("first_name", "last_name")
    @classmethod
    def validate_name_format(cls, v):
        """Ensure names contain only letters and spaces."""
        if not v.replace(" ", "").isalpha():
            raise ValueError("Name should only contain letters and spaces")
        return v


class AdminContact(BaseModel):
    """Structured contact input for admin creation."""
    country_code: str = Field(..., json_schema_extra={"example": "+91"})
    phone_number: str = Field(..., json_schema_extra={"example": "9876543210"})


class AdminCreate(BaseModel):
    """Request body for creating a new admin account.

    employee_id is auto-generated by the system in ZNBAD000001 format.
    department has been removed from the schema.
    """
    email: EmailStr = Field(..., description="Must be lowercase only")
    password: str = Field(..., min_length=12, description="Minimum 12 characters")
    confirm_password: str = Field(..., description="Must match password exactly")
    full_name: AdminFullName
    contact: AdminContact
    role: Role = Role.MANAGER

    @field_validator("email", mode="before")
    @classmethod
    def validate_lowercase_email(cls, v):
        """Reject mixed-case or uppercase emails. Only lowercase accepted."""
        if isinstance(v, str):
            stripped = v.strip()
            if stripped != stripped.lower():
                raise ValueError("Email must be in lowercase only")
            return stripped
        return v

    @field_validator("role")
    @classmethod
    def validate_role(cls, v):
        """Prevent creation of SUPERADMIN or USER role admins."""
        if v == Role.SUPERADMIN:
            raise ValueError("Cannot create SUPERADMIN role")
        if v == Role.USER:
            raise ValueError("Cannot assign USER role to an Admin")
        return v


class AdminEmailLogin(BaseModel):
    """Login request body for admin authentication."""
    email: EmailStr
    password: str


class AdminResponse(BaseModel):
    """Response schema for admin details."""
    id: UUID
    email: EmailStr
    full_name: str
    role: Role
    employee_id: Optional[str] = None
    created_at: datetime

    model_config = ConfigDict(
        from_attributes=True,
        populate_by_name=True,
        json_encoders={
            datetime: lambda v: getattr(v, "isoformat", lambda: str(v))(),
            UUID: lambda v: str(v)
        }
    )


class TokenResponse(BaseModel):
    """Token response for admin login."""
    access_token: str
    token_type: str = "bearer"
    message: str
    login_timestamp: str


class AdminCreationResponse(BaseModel):
    """Response after successful admin creation."""
    admin: str
    employee_id: str
    created_at: datetime
    created_by: str

    model_config = ConfigDict(
        from_attributes=True,
        json_encoders={
            datetime: lambda v: getattr(v, "isoformat", lambda: str(v))(),
            UUID: lambda v: str(v)
        }
    )
