"""Admin schema restructure

Revision ID: 081914b6b248
Revises: 72df4c15f355
Create Date: 2026-04-08 19:27:50.002349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '081914b6b248'
down_revision: Union[str, Sequence[str], None] = '72df4c15f355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'employee_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_unique_constraint(None, 'admins', ['employee_id'])
    op.drop_column('admins', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'admins', type_='unique')
    op.alter_column('admins', 'employee_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
