"""Add foreign tx fields to transaction and credit_account

Revision ID: 124dde059aa4
Revises: 9559fb01c696
Create Date: 2026-04-14 15:29:50.932944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '124dde059aa4'
down_revision: Union[str, Sequence[str], None] = '9559fb01c696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_account', sa.Column('home_country', sa.String(length=2), nullable=False))
    op.add_column('transactions', sa.Column('is_foreign', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('foreign_fee', sa.Numeric(precision=15, scale=2), nullable=True))
    op.alter_column('transactions', 'merchant_country',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'merchant_country',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    op.drop_column('transactions', 'foreign_fee')
    op.drop_column('transactions', 'is_foreign')
    op.drop_column('credit_account', 'home_country')
    # ### end Alembic commands ###
