"""add_billing_fraud_idempotency_models

Revision ID: 137795526f55
Revises: b87bba2dff98
Create Date: 2026-04-02 16:12:54.875938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '137795526f55'
down_revision: Union[str, Sequence[str], None] = 'b87bba2dff98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('key')
    )

    op.drop_index(op.f('ix_refunds_original_txn_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_refund_txn_id'), table_name='refunds')
    op.drop_table('refunds')
    op.add_column('payments', sa.Column('credit_account_id', sa.UUID(), nullable=False))
    op.add_column('payments', sa.Column('statement_id', sa.UUID(), nullable=True))
    op.add_column('payments', sa.Column('reference_no', sa.String(length=64), nullable=False))
    op.add_column('payments', sa.Column('allocated_fees', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('payments', sa.Column('allocated_interest', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('payments', sa.Column('allocated_cash_advance', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('payments', sa.Column('allocated_purchases', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('payments', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'payments', 'statements', ['statement_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'credit_account', ['credit_account_id'], ['id'])
    op.drop_column('payments', 'currency')
    op.drop_column('payments', 'allocation_breakdown')
    op.drop_column('payments', 'remarks')
    op.drop_column('payments', 'source_reference')
    op.add_column('statement_line_items', sa.Column('transaction_date', sa.Date(), nullable=False))
    op.alter_column('statement_line_items', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_column('statement_line_items', 'line_date')
    op.add_column('statements', sa.Column('credit_account_id', sa.UUID(), nullable=False))
    op.add_column('statements', sa.Column('total_interest', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('statements', sa.Column('total_payments', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('statements', sa.Column('total_amount_due', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('statements', sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('statements', sa.Column('generated_by', sa.UUID(), nullable=True))
    op.alter_column('statements', 'payment_due_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('statements', 'status',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_statement_card_cycle'), table_name='statements')
    op.create_index('ix_stmt_account_cycle', 'statements', ['credit_account_id', 'cycle_end'], unique=False)
    op.create_index('ix_stmt_card_cycle', 'statements', ['card_id', 'cycle_start', 'cycle_end'], unique=False)
    op.create_foreign_key(None, 'statements', 'admins', ['generated_by'], ['id'])
    op.create_foreign_key(None, 'statements', 'credit_account', ['credit_account_id'], ['id'])
    op.drop_column('statements', 'min_paid')
    op.drop_column('statements', 'fully_paid')
    op.add_column('transactions', sa.Column('risk_flag', sa.Boolean(), nullable=False))
    op.add_column('transactions', sa.Column('risk_notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'risk_notes')
    op.drop_column('transactions', 'risk_flag')
    op.add_column('statements', sa.Column('fully_paid', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('statements', sa.Column('min_paid', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'statements', type_='foreignkey')
    op.drop_constraint(None, 'statements', type_='foreignkey')
    op.drop_index('ix_stmt_card_cycle', table_name='statements')
    op.drop_index('ix_stmt_account_cycle', table_name='statements')
    op.create_index(op.f('ix_statement_card_cycle'), 'statements', ['card_id', 'cycle_start', 'cycle_end'], unique=False)
    op.alter_column('statements', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    op.alter_column('statements', 'payment_due_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('statements', 'generated_by')
    op.drop_column('statements', 'generated_at')
    op.drop_column('statements', 'total_amount_due')
    op.drop_column('statements', 'total_payments')
    op.drop_column('statements', 'total_interest')
    op.drop_column('statements', 'credit_account_id')
    op.add_column('statement_line_items', sa.Column('line_date', sa.DATE(), autoincrement=False, nullable=False))
    op.alter_column('statement_line_items', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('statement_line_items', 'transaction_date')
    op.add_column('payments', sa.Column('source_reference', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('allocation_breakdown', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'created_by')
    op.drop_column('payments', 'allocated_purchases')
    op.drop_column('payments', 'allocated_cash_advance')
    op.drop_column('payments', 'allocated_interest')
    op.drop_column('payments', 'allocated_fees')
    op.drop_column('payments', 'reference_no')
    op.drop_column('payments', 'statement_id')
    op.drop_column('payments', 'credit_account_id')
    op.create_table('refunds',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('original_txn_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('refund_txn_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('merchant_reference', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('partial', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['original_txn_id'], ['transactions.id'], name=op.f('refunds_original_txn_id_fkey')),
    sa.ForeignKeyConstraint(['refund_txn_id'], ['transactions.id'], name=op.f('refunds_refund_txn_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('refunds_pkey'))
    )
    op.create_index(op.f('ix_refunds_refund_txn_id'), 'refunds', ['refund_txn_id'], unique=False)
    op.create_index(op.f('ix_refunds_original_txn_id'), 'refunds', ['original_txn_id'], unique=False)

    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
