"""Add full CIF structure

Revision ID: 147166bc179f
Revises: 7dad48df3617
Create Date: 2026-02-25 17:35:47.297092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '147166bc179f'
down_revision: Union[str, Sequence[str], None] = '7dad48df3617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_profile_id', sa.UUID(), nullable=True),
    sa.Column('address_line_1', sa.String(), nullable=False),
    sa.Column('address_line_2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('residence_type', sa.String(), nullable=True),
    sa.Column('years_at_address', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_profile_id'], ['customer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employment_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_profile_id', sa.UUID(), nullable=True),
    sa.Column('employment_type', sa.Enum('SALARIED', 'SELF_EMPLOYED', 'STUDENT', 'RETIRED', 'UNEMPLOYED', name='employmenttype'), nullable=True),
    sa.Column('employer_name', sa.String(), nullable=True),
    sa.Column('employer_country', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('annual_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_profile_id'], ['customer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_information',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_profile_id', sa.UUID(), nullable=True),
    sa.Column('net_annual_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('monthly_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('other_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('housing_payment', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('other_obligations', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('bankruptcy_flag', sa.Boolean(), nullable=True),
    sa.Column('default_history_flag', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_profile_id'], ['customer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kyc_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_profile_id', sa.UUID(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('document_number_hash', sa.String(), nullable=True),
    sa.Column('document_file_path', sa.String(), nullable=True),
    sa.Column('verified_status', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_profile_id'], ['customer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('auth_credentials', sa.Column('password_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('auth_credentials', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('auth_credentials', 'passcode_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('auth_credentials', 'created_at')
    op.add_column('customer_profiles', sa.Column('suffix', sa.String(), nullable=True))
    op.add_column('customer_profiles', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.alter_column('customer_profiles', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('customer_profiles', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('customer_profiles', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('customer_profiles', 'country_of_residence',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('customer_profiles', 'nationality',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('customer_profiles', 'date_of_birth',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=True)
    kyc_enum = sa.Enum(
    'INCOMPLETE',
    'PENDING',
    'VERIFIED',
    'REJECTED',
    name='kycstatus'
    )
    kyc_enum.create(op.get_bind(), checkfirst=True)
    op.execute(
        "ALTER TABLE customer_profiles "
        "ALTER COLUMN kyc_status "
        "TYPE kycstatus "
        "USING kyc_status::kycstatus"
    )
    op.add_column('users', sa.Column('country_code', sa.String(), nullable=False))
    op.drop_constraint(op.f('users_phone_number_key'), 'users', type_='unique')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('USER', 'ADMIN', name='userrole'), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('users_phone_number_key'), 'users', ['phone_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'country_code')
    op.alter_column('customer_profiles', 'kyc_status',
               existing_type=sa.Enum('INCOMPLETE', 'PENDING', 'VERIFIED', 'REJECTED', name='kycstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('customer_profiles', 'date_of_birth',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('customer_profiles', 'nationality',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('customer_profiles', 'country_of_residence',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('customer_profiles', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('customer_profiles', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('customer_profiles', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('customer_profiles', 'updated_by')
    op.drop_column('customer_profiles', 'suffix')
    op.add_column('auth_credentials', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('auth_credentials', 'passcode_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('auth_credentials', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('auth_credentials', 'password_updated_at')
    op.drop_table('kyc_records')
    op.drop_table('financial_information')
    op.drop_table('employment_details')
    op.drop_table('customer_addresses')
    # ### end Alembic commands ###
