"""expand customer profile for cif

Revision ID: 1c77d11e2046
Revises: ef34d096df09
Create Date: 2026-02-26 15:04:14.587893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c77d11e2046'
down_revision: Union[str, Sequence[str], None] = 'ef34d096df09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_profiles', sa.Column('citizenship_document_type', sa.String(), nullable=True))
    op.add_column('customer_profiles', sa.Column('citizenship_number_hash', sa.String(), nullable=True))
    op.add_column('customer_profiles', sa.Column('primary_mobile_country_code', sa.String(), nullable=True))
    op.add_column('customer_profiles', sa.Column('primary_mobile_number', sa.String(), nullable=True))
    op.add_column('customer_profiles', sa.Column('alternate_mobile_number', sa.String(), nullable=True))
    op.add_column('customer_profiles', sa.Column('preferred_communication', sa.String(), nullable=True))
    op.add_column('customer_profiles', sa.Column('timezone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_profiles', 'timezone')
    op.drop_column('customer_profiles', 'preferred_communication')
    op.drop_column('customer_profiles', 'alternate_mobile_number')
    op.drop_column('customer_profiles', 'primary_mobile_number')
    op.drop_column('customer_profiles', 'primary_mobile_country_code')
    op.drop_column('customer_profiles', 'citizenship_number_hash')
    op.drop_column('customer_profiles', 'citizenship_document_type')
    # ### end Alembic commands ###
