"""Add file_content to KYCDocumentSubmission

Revision ID: 28de87878dc9
Revises: 6e5f2d52e2ad
Create Date: 2026-04-03 01:26:05.902137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28de87878dc9'
down_revision: Union[str, Sequence[str], None] = '6e5f2d52e2ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc_document_submissions', sa.Column('file_content', sa.LargeBinary(), nullable=True))
    op.add_column('kyc_document_submissions', sa.Column('file_name', sa.String(), nullable=True))
    op.add_column('kyc_document_submissions', sa.Column('file_mime_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kyc_document_submissions', 'file_mime_type')
    op.drop_column('kyc_document_submissions', 'file_name')
    op.drop_column('kyc_document_submissions', 'file_content')
    # ### end Alembic commands ###
