"""Add detailed application fields

Revision ID: 2c69b4ec0799
Revises: f50f53ff89d5
Create Date: 2026-03-02 18:36:51.217835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c69b4ec0799'
down_revision: Union[str, Sequence[str], None] = 'f50f53ff89d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('previous_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bureau_report',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('bureau_score', sa.Integer(), nullable=False),
    sa.Column('report_reference_id', sa.String(), nullable=False),
    sa.Column('bureau_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['credit_card_application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_decision',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('DRAFT', 'SUBMITTED', 'PENDING', 'ADMIN_REVIEW_PENDING', 'APPROVED', 'REJECTED', 'ACCOUNT_CREATED', name='applicationstatus', native_enum=False), nullable=False),
    sa.Column('override_flag', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['credit_card_application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fraud_flag',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('flag_code', sa.Enum('RESIDENCY_MISMATCH', 'INCOME_MISMATCH', 'HIGH_VELOCITY', 'SANCTIONS_MATCH', name='fraudflagtype', native_enum=False), nullable=False),
    sa.Column('flag_description', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('flagged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['credit_card_application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_assessment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('risk_band', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH', name='riskband', native_enum=False), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('assessment_explanation', sa.String(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['credit_card_application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('card', sa.Column('expiry_date_masked', sa.String(), nullable=False))
    op.add_column('card', sa.Column('cvv_encrypted', sa.String(), nullable=False))
    op.add_column('card', sa.Column('cvv_masked', sa.String(), nullable=False))
    op.add_column('credit_card_application', sa.Column('income_frequency', sa.String(), nullable=True))
    op.add_column('credit_card_application', sa.Column('occupation', sa.String(), nullable=True))
    op.add_column('credit_card_application', sa.Column('employer_name', sa.String(), nullable=True))
    op.add_column('credit_card_application', sa.Column('work_experience_years', sa.Integer(), nullable=True))
    op.add_column('credit_card_application', sa.Column('existing_emis_monthly', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('credit_card_application', sa.Column('has_existing_credit_card', sa.Boolean(), nullable=True))
    op.add_column('credit_card_application', sa.Column('existing_cards_count', sa.Integer(), nullable=True))
    op.add_column('credit_card_application', sa.Column('approx_credit_limit_total', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('credit_card_application', sa.Column('residential_status', sa.String(), nullable=True))
    op.add_column('credit_card_application', sa.Column('years_at_current_address', sa.Integer(), nullable=True))
    op.add_column('credit_card_application', sa.Column('preferred_billing_cycle', sa.String(), nullable=True))
    op.add_column('credit_card_application', sa.Column('statement_delivery_mode', sa.String(), nullable=True))
    op.add_column('credit_card_application', sa.Column('card_delivery_address_type', sa.String(), nullable=True))
    op.add_column('credit_card_application', sa.Column('preferred_branch_code', sa.String(), nullable=True))
    op.add_column('credit_card_application', sa.Column('nominee_name', sa.String(), nullable=True))
    op.add_column('credit_card_application', sa.Column('nominee_relationship', sa.String(), nullable=True))
    op.add_column('credit_card_application', sa.Column('consent_terms_accepted', sa.Boolean(), nullable=True))
    op.add_column('credit_card_application', sa.Column('consent_credit_bureau_check', sa.Boolean(), nullable=True))
    op.add_column('credit_card_application', sa.Column('consent_marketing_communication', sa.Boolean(), nullable=True))
    op.add_column('credit_card_application', sa.Column('application_declaration_accepted', sa.Boolean(), nullable=True))
    op.alter_column('credit_card_application', 'application_status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('DRAFT', 'SUBMITTED', 'PENDING', 'ADMIN_REVIEW_PENDING', 'APPROVED', 'REJECTED', 'ACCOUNT_CREATED', name='applicationstatus', native_enum=False),
               existing_nullable=True)
    op.drop_column('credit_card_application', 'risk_band')
    op.drop_column('credit_card_application', 'cibil_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_card_application', sa.Column('cibil_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('credit_card_application', sa.Column('risk_band', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('credit_card_application', 'application_status',
               existing_type=sa.Enum('DRAFT', 'SUBMITTED', 'PENDING', 'ADMIN_REVIEW_PENDING', 'APPROVED', 'REJECTED', 'ACCOUNT_CREATED', name='applicationstatus', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)
    op.drop_column('credit_card_application', 'application_declaration_accepted')
    op.drop_column('credit_card_application', 'consent_marketing_communication')
    op.drop_column('credit_card_application', 'consent_credit_bureau_check')
    op.drop_column('credit_card_application', 'consent_terms_accepted')
    op.drop_column('credit_card_application', 'nominee_relationship')
    op.drop_column('credit_card_application', 'nominee_name')
    op.drop_column('credit_card_application', 'preferred_branch_code')
    op.drop_column('credit_card_application', 'card_delivery_address_type')
    op.drop_column('credit_card_application', 'statement_delivery_mode')
    op.drop_column('credit_card_application', 'preferred_billing_cycle')
    op.drop_column('credit_card_application', 'years_at_current_address')
    op.drop_column('credit_card_application', 'residential_status')
    op.drop_column('credit_card_application', 'approx_credit_limit_total')
    op.drop_column('credit_card_application', 'existing_cards_count')
    op.drop_column('credit_card_application', 'has_existing_credit_card')
    op.drop_column('credit_card_application', 'existing_emis_monthly')
    op.drop_column('credit_card_application', 'work_experience_years')
    op.drop_column('credit_card_application', 'employer_name')
    op.drop_column('credit_card_application', 'occupation')
    op.drop_column('credit_card_application', 'income_frequency')
    op.drop_column('card', 'cvv_masked')
    op.drop_column('card', 'cvv_encrypted')
    op.drop_column('card', 'expiry_date_masked')
    op.drop_table('risk_assessment')
    op.drop_table('fraud_flag')
    op.drop_table('credit_decision')
    op.drop_table('bureau_report')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
