"""add missing readable_id and other fields to issuance models

Revision ID: 32648c6db8d9
Revises: 923cf6777035
Create Date: 2026-03-12 15:33:39.868099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32648c6db8d9'
down_revision: Union[str, Sequence[str], None] = '923cf6777035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_activation_otp',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('otp_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('card', sa.Column('readable_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_card_readable_id'), 'card', ['readable_id'], unique=True)
    op.add_column('credit_account', sa.Column('readable_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_credit_account_readable_id'), 'credit_account', ['readable_id'], unique=True)
    op.add_column('credit_card_application', sa.Column('readable_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_credit_card_application_readable_id'), 'credit_card_application', ['readable_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_card_application_readable_id'), table_name='credit_card_application')
    op.drop_column('credit_card_application', 'readable_id')
    op.drop_index(op.f('ix_credit_account_readable_id'), table_name='credit_account')
    op.drop_column('credit_account', 'readable_id')
    op.drop_index(op.f('ix_card_readable_id'), table_name='card')
    op.drop_column('card', 'readable_id')
    op.drop_table('card_activation_otp')
    # ### end Alembic commands ###
