"""module_4_underwriting_audit_refactor

Revision ID: 367d6abc0f8e
Revises: 22152f44a413
Create Date: 2026-04-06 16:29:05.931190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '367d6abc0f8e'
down_revision: Union[str, Sequence[str], None] = '22152f44a413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('SUPERADMIN', 'ADMIN', 'MANAGER', 'SALES', 'USER', name='role', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'MANAGER'::character varying"))
    op.add_column('bureau_report', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('bureau_report', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bureau_report', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('card', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('card', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('card', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('credit_account', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('credit_account', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('credit_account', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('credit_card_application', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('credit_card_application', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('credit_card_application', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('credit_decision', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('credit_decision', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('credit_decision', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('fraud_flag', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('fraud_flag', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('fraud_flag', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('risk_assessment', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('risk_assessment', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('risk_assessment', sa.Column('updated_by', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_assessment', 'updated_by')
    op.drop_column('risk_assessment', 'updated_at')
    op.drop_column('risk_assessment', 'created_at')
    op.drop_column('fraud_flag', 'updated_by')
    op.drop_column('fraud_flag', 'updated_at')
    op.drop_column('fraud_flag', 'created_at')
    op.drop_column('credit_decision', 'updated_by')
    op.drop_column('credit_decision', 'updated_at')
    op.drop_column('credit_decision', 'created_at')
    op.drop_column('credit_card_application', 'updated_by')
    op.drop_column('credit_card_application', 'updated_at')
    op.drop_column('credit_card_application', 'created_at')
    op.drop_column('credit_account', 'updated_by')
    op.drop_column('credit_account', 'updated_at')
    op.drop_column('credit_account', 'created_at')
    op.drop_column('card', 'updated_by')
    op.drop_column('card', 'updated_at')
    op.drop_column('card', 'created_at')
    op.drop_column('bureau_report', 'updated_by')
    op.drop_column('bureau_report', 'updated_at')
    op.drop_column('bureau_report', 'created_at')
    op.alter_column('admins', 'role',
               existing_type=sa.Enum('SUPERADMIN', 'ADMIN', 'MANAGER', 'SALES', 'USER', name='role', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'MANAGER'::character varying"))
    # ### end Alembic commands ###
