"""add_is_kyc_completed

Revision ID: 3c3e8e6d0808
Revises: f16ca6ef7f52
Create Date: 2026-03-01 14:30:30.441043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c3e8e6d0808'
down_revision: Union[str, Sequence[str], None] = 'f16ca6ef7f52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_kyc_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_kyc_completed')
    # ### end Alembic commands ###
