"""Add Bill and Fee models

Revision ID: 4007e3179af8
Revises: 64df13ad0286
Create Date: 2026-04-15 00:13:48.067138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4007e3179af8'
down_revision: Union[str, Sequence[str], None] = '64df13ad0286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('billing_cycle_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('billing_cycle_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('previous_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('new_charges', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('foreign_fees_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('interest', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('other_fees', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('credits', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_due', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('min_payment_due', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transactions_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['credit_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bills_account_id'), 'bills', ['account_id'], unique=False)
    op.add_column('fees', sa.Column('account_id', sa.UUID(), nullable=True))
    op.add_column('fees', sa.Column('status', sa.String(length=20), server_default="POSTED", nullable=False))
    op.add_column('fees', sa.Column('applied_to_bill_id', sa.UUID(), nullable=True))
    op.add_column('fees', sa.Column('reason', sa.Text(), nullable=True))
    op.add_column('fees', sa.Column('assessed_by', sa.String(), nullable=True))
    op.create_foreign_key(None, 'fees', 'bills', ['applied_to_bill_id'], ['id'])
    op.create_foreign_key(None, 'fees', 'credit_account', ['account_id'], ['id'])
    op.add_column('payments', sa.Column('bill_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('payments_statement_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'bills', ['bill_id'], ['id'])
    op.drop_column('payments', 'statement_id')
    op.add_column('statements', sa.Column('account_id', sa.UUID(), nullable=True))
    op.add_column('statements', sa.Column('bill_id', sa.UUID(), nullable=True))
    op.add_column('statements', sa.Column('billing_cycle', sa.String(length=7), nullable=True))
    op.add_column('statements', sa.Column('total_charges', sa.Numeric(precision=15, scale=2), server_default="0", nullable=False))
    op.add_column('statements', sa.Column('total_foreign_fees', sa.Numeric(precision=15, scale=2), server_default="0", nullable=False))
    op.add_column('statements', sa.Column('interest_charged', sa.Numeric(precision=15, scale=2), server_default="0", nullable=False))
    op.add_column('statements', sa.Column('total_due', sa.Numeric(precision=15, scale=2), server_default="0", nullable=False))
    op.add_column('statements', sa.Column('min_payment_due', sa.Numeric(precision=15, scale=2), server_default="0", nullable=False))
    op.add_column('statements', sa.Column('due_date', sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False))
    op.drop_index(op.f('ix_stmt_account_cycle'), table_name='statements')
    op.drop_index(op.f('ix_stmt_card_cycle'), table_name='statements')
    op.create_index('ix_stmt_card_cycle', 'statements', ['card_id', 'billing_cycle'], unique=False)
    op.create_index(op.f('ix_statements_bill_id'), 'statements', ['bill_id'], unique=False)
    op.drop_constraint(op.f('statements_credit_account_id_fkey'), 'statements', type_='foreignkey')
    op.drop_constraint(op.f('statements_generated_by_fkey'), 'statements', type_='foreignkey')
    op.create_foreign_key(None, 'statements', 'bills', ['bill_id'], ['id'])
    op.create_foreign_key(None, 'statements', 'credit_account', ['account_id'], ['id'])
    op.drop_column('statements', 'total_fees')
    op.drop_column('statements', 'generated_by')
    op.drop_column('statements', 'cycle_start')
    op.drop_column('statements', 'opening_balance')
    op.drop_column('statements', 'cycle_end')
    op.drop_column('statements', 'credit_account_id')
    op.drop_column('statements', 'total_purchases')
    op.drop_column('statements', 'total_credits')
    op.drop_column('statements', 'updated_at')
    op.drop_column('statements', 'created_at')
    op.drop_column('statements', 'total_interest')
    op.drop_column('statements', 'status')
    op.drop_column('statements', 'payment_due_date')
    op.drop_column('statements', 'closing_balance')
    op.drop_column('statements', 'minimum_due')
    op.drop_column('statements', 'total_amount_due')
    op.drop_column('statements', 'total_payments')
    op.drop_column('statements', 'total_cash_advances')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statements', sa.Column('total_cash_advances', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('statements', sa.Column('total_payments', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('statements', sa.Column('total_amount_due', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('statements', sa.Column('minimum_due', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('statements', sa.Column('closing_balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('statements', sa.Column('payment_due_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('statements', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('statements', sa.Column('total_interest', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('statements', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('statements', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('statements', sa.Column('total_credits', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('statements', sa.Column('total_purchases', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('statements', sa.Column('credit_account_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('statements', sa.Column('cycle_end', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('statements', sa.Column('opening_balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('statements', sa.Column('cycle_start', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('statements', sa.Column('generated_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('statements', sa.Column('total_fees', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'statements', type_='foreignkey')
    op.drop_constraint(None, 'statements', type_='foreignkey')
    op.create_foreign_key(op.f('statements_generated_by_fkey'), 'statements', 'admins', ['generated_by'], ['id'])
    op.create_foreign_key(op.f('statements_credit_account_id_fkey'), 'statements', 'credit_account', ['credit_account_id'], ['id'])
    op.drop_index(op.f('ix_statements_bill_id'), table_name='statements')
    op.drop_index('ix_stmt_card_cycle', table_name='statements')
    op.create_index(op.f('ix_stmt_card_cycle'), 'statements', ['card_id', 'cycle_start', 'cycle_end'], unique=False)
    op.create_index(op.f('ix_stmt_account_cycle'), 'statements', ['credit_account_id', 'cycle_end'], unique=False)
    op.drop_column('statements', 'due_date')
    op.drop_column('statements', 'min_payment_due')
    op.drop_column('statements', 'total_due')
    op.drop_column('statements', 'interest_charged')
    op.drop_column('statements', 'total_foreign_fees')
    op.drop_column('statements', 'total_charges')
    op.drop_column('statements', 'billing_cycle')
    op.drop_column('statements', 'bill_id')
    op.drop_column('statements', 'account_id')
    op.add_column('payments', sa.Column('statement_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_statement_id_fkey'), 'payments', 'statements', ['statement_id'], ['id'])
    op.drop_column('payments', 'bill_id')
    op.drop_constraint(None, 'fees', type_='foreignkey')
    op.drop_constraint(None, 'fees', type_='foreignkey')
    op.drop_column('fees', 'assessed_by')
    op.drop_column('fees', 'reason')
    op.drop_column('fees', 'applied_to_bill_id')
    op.drop_column('fees', 'status')
    op.drop_column('fees', 'account_id')
    op.drop_index(op.f('ix_bills_account_id'), table_name='bills')
    op.drop_table('bills')
    # ### end Alembic commands ###
