"""Remove unnecessary application fields

Revision ID: 429d5e2ccdc9
Revises: 2c69b4ec0799
Create Date: 2026-03-02 18:49:01.280231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '429d5e2ccdc9'
down_revision: Union[str, Sequence[str], None] = '2c69b4ec0799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_card_application', 'preferred_branch_code')
    op.drop_column('credit_card_application', 'card_delivery_address_type')
    op.drop_column('credit_card_application', 'residential_status')
    op.drop_column('credit_card_application', 'preferred_billing_cycle')
    op.drop_column('credit_card_application', 'years_at_current_address')
    op.drop_column('credit_card_application', 'statement_delivery_mode')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_card_application', sa.Column('statement_delivery_mode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('credit_card_application', sa.Column('years_at_current_address', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('credit_card_application', sa.Column('preferred_billing_cycle', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('credit_card_application', sa.Column('residential_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('credit_card_application', sa.Column('card_delivery_address_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('credit_card_application', sa.Column('preferred_branch_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
