"""Add admins table

Revision ID: 6011f54b952f
Revises: 0d66cefbc956
Create Date: 2026-03-02 07:33:05.192269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6011f54b952f'
down_revision: Union[str, Sequence[str], None] = '0d66cefbc956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM admins;")
    op.add_column('admins', sa.Column('password_hash', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'password_hash')
    # ### end Alembic commands ###
