"""Add IdempotencyLog table

Revision ID: 64df13ad0286
Revises: 124dde059aa4
Create Date: 2026-04-14 16:21:56.358585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64df13ad0286'
down_revision: Union[str, Sequence[str], None] = '124dde059aa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_idemp_key_created', 'idempotency_log', ['idempotency_key', 'created_at'], unique=False)
    op.create_index(op.f('ix_idempotency_log_idempotency_key'), 'idempotency_log', ['idempotency_key'], unique=False)
    op.drop_index(op.f('ix_idemp_fingerprint_created'), table_name='transaction_idempotency')
    op.drop_index(op.f('ix_transaction_idempotency_fingerprint'), table_name='transaction_idempotency')
    op.drop_table('transaction_idempotency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_idempotency',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('fingerprint', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('transaction_idempotency_transaction_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('transaction_idempotency_pkey'))
    )
    op.create_index(op.f('ix_transaction_idempotency_fingerprint'), 'transaction_idempotency', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_idemp_fingerprint_created'), 'transaction_idempotency', ['fingerprint', 'created_at'], unique=False)
    op.drop_index(op.f('ix_idempotency_log_idempotency_key'), table_name='idempotency_log')
    op.drop_index('ix_idemp_key_created', table_name='idempotency_log')
    op.drop_table('idempotency_log')
    # ### end Alembic commands ###
