"""add_statements_payments_fraud_idempotency

Revision ID: 6e5f2d52e2ad
Revises: 137795526f55
Create Date: 2026-04-02 16:26:54.060567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e5f2d52e2ad'
down_revision: Union[str, Sequence[str], None] = '137795526f55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
