"""feat(bureau): add bureau_scores table with factor breakdown columns

Revision ID: 72df4c15f355
Revises: 367d6abc0f8e
Create Date: 2026-04-07 12:54:42.436062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72df4c15f355'
down_revision: Union[str, Sequence[str], None] = '367d6abc0f8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bureau_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('risk_band', sa.Enum('POOR', 'FAIR', 'GOOD', 'VERY_GOOD', 'EXCELLENT', name='bureauriskband'), nullable=False),
    sa.Column('trigger_event', sa.Enum('TRANSACTION_SETTLED', 'PAYMENT_MADE', 'MANUAL_REQUEST', 'SCHEDULED', name='scoretrigger'), nullable=False),
    sa.Column('trigger_ref_id', sa.UUID(), nullable=True),
    sa.Column('payment_history_score', sa.Integer(), nullable=False),
    sa.Column('utilisation_score', sa.Integer(), nullable=False),
    sa.Column('credit_history_score', sa.Integer(), nullable=False),
    sa.Column('transaction_behaviour_score', sa.Integer(), nullable=False),
    sa.Column('derogatory_score', sa.Integer(), nullable=False),
    sa.Column('on_time_payment_count', sa.Integer(), nullable=False),
    sa.Column('late_payment_count', sa.Integer(), nullable=False),
    sa.Column('missed_payment_count', sa.Integer(), nullable=False),
    sa.Column('current_utilisation_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('account_age_days', sa.Integer(), nullable=False),
    sa.Column('total_transactions_90d', sa.Integer(), nullable=False),
    sa.Column('disputes_90d', sa.Integer(), nullable=False),
    sa.Column('chargebacks_total', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('computed_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bureau_scores_computed_at'), 'bureau_scores', ['computed_at'], unique=False)
    op.create_index(op.f('ix_bureau_scores_user_id'), 'bureau_scores', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bureau_scores_user_id'), table_name='bureau_scores')
    op.drop_index(op.f('ix_bureau_scores_computed_at'), table_name='bureau_scores')
    op.drop_table('bureau_scores')
    # ### end Alembic commands ###
