"""add_job_log_and_bill_models

Revision ID: 7f47d45dc184
Revises: 4007e3179af8
Create Date: 2026-04-15 00:35:25.810080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f47d45dc184'
down_revision: Union[str, Sequence[str], None] = '4007e3179af8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_name', sa.String(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cycle_date', sa.Date(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_logs_job_name'), 'job_logs', ['job_name'], unique=True)
    op.alter_column('statements', 'account_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('statements', 'bill_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('statements', 'billing_cycle',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statements', 'billing_cycle',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)
    op.alter_column('statements', 'bill_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('statements', 'account_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_job_logs_job_name'), table_name='job_logs')
    op.drop_table('job_logs')
    # ### end Alembic commands ###
