"""Add token_blacklist table

Revision ID: 9559fb01c696
Revises: 081914b6b248
Create Date: 2026-04-13 12:58:08.936454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9559fb01c696'
down_revision: Union[str, Sequence[str], None] = '081914b6b248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prohibited_countries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=False),
    sa.Column('restriction_type', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prohibited_countries_country_code'), 'prohibited_countries', ['country_code'], unique=True)
    op.create_table('token_blacklist',
    sa.Column('jti', sa.String(length=50), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index(op.f('ix_token_blacklist_jti'), 'token_blacklist', ['jti'], unique=False)
    op.create_table('card_velocity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('window', sa.String(length=10), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_velocity_card_id'), 'card_velocity', ['card_id'], unique=False)
    op.create_index('ix_velocity_card_window', 'card_velocity', ['card_id', 'window'], unique=False)
    op.create_table('transaction_idempotency',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_idemp_fingerprint_created', 'transaction_idempotency', ['fingerprint', 'created_at'], unique=False)
    op.create_index(op.f('ix_transaction_idempotency_fingerprint'), 'transaction_idempotency', ['fingerprint'], unique=False)
    op.drop_table('fraud_flags')
    op.alter_column('credit_product_compliance_metadata', 'jurisdiction',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('INDIA', 'USA', 'UK', 'CANADA', 'AUSTRALIA', 'UAE', 'PAKISTAN', 'MYANMAR', 'SYRIA', 'YEMEN', 'AFGHANISTAN', 'SOMALIA', 'SUDAN', 'SOUTH_SUDAN', 'LIBYA', 'LEBANON', 'IRAQ', 'ZIMBABWE', 'VENEZUELA', 'CONGO', 'NORTH_KOREA', 'IRAN', name='country', native_enum=False),
               existing_nullable=True)
    op.alter_column('customer_profiles', 'country_of_residence',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('INDIA', 'USA', 'UK', 'CANADA', 'AUSTRALIA', 'UAE', 'PAKISTAN', 'MYANMAR', 'SYRIA', 'YEMEN', 'AFGHANISTAN', 'SOMALIA', 'SUDAN', 'SOUTH_SUDAN', 'LIBYA', 'LEBANON', 'IRAQ', 'ZIMBABWE', 'VENEZUELA', 'CONGO', 'NORTH_KOREA', 'IRAN', name='country', native_enum=False),
               existing_nullable=True)
    op.alter_column('customer_profiles', 'nationality',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('INDIA', 'USA', 'UK', 'CANADA', 'AUSTRALIA', 'UAE', 'PAKISTAN', 'MYANMAR', 'SYRIA', 'YEMEN', 'AFGHANISTAN', 'SOMALIA', 'SUDAN', 'SOUTH_SUDAN', 'LIBYA', 'LEBANON', 'IRAQ', 'ZIMBABWE', 'VENEZUELA', 'CONGO', 'NORTH_KOREA', 'IRAN', name='country', native_enum=False),
               existing_nullable=True)
    op.add_column('disputes', sa.Column('raised_by_user_id', sa.String(length=100), nullable=True))
    op.add_column('disputes', sa.Column('decision', sa.String(length=20), nullable=True))
    op.add_column('disputes', sa.Column('decision_reason', sa.Text(), nullable=True))
    op.drop_column('disputes', 'resolution')
    op.add_column('payments', sa.Column('payment_type', sa.String(length=20), nullable=False))
    op.add_column('payments', sa.Column('remaining_balance', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('payments', sa.Column('is_partial', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'is_partial')
    op.drop_column('payments', 'remaining_balance')
    op.drop_column('payments', 'payment_type')
    op.add_column('disputes', sa.Column('resolution', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('disputes', 'decision_reason')
    op.drop_column('disputes', 'decision')
    op.drop_column('disputes', 'raised_by_user_id')
    op.alter_column('customer_profiles', 'nationality',
               existing_type=sa.Enum('INDIA', 'USA', 'UK', 'CANADA', 'AUSTRALIA', 'UAE', 'PAKISTAN', 'MYANMAR', 'SYRIA', 'YEMEN', 'AFGHANISTAN', 'SOMALIA', 'SUDAN', 'SOUTH_SUDAN', 'LIBYA', 'LEBANON', 'IRAQ', 'ZIMBABWE', 'VENEZUELA', 'CONGO', 'NORTH_KOREA', 'IRAN', name='country', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)
    op.alter_column('customer_profiles', 'country_of_residence',
               existing_type=sa.Enum('INDIA', 'USA', 'UK', 'CANADA', 'AUSTRALIA', 'UAE', 'PAKISTAN', 'MYANMAR', 'SYRIA', 'YEMEN', 'AFGHANISTAN', 'SOMALIA', 'SUDAN', 'SOUTH_SUDAN', 'LIBYA', 'LEBANON', 'IRAQ', 'ZIMBABWE', 'VENEZUELA', 'CONGO', 'NORTH_KOREA', 'IRAN', name='country', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)
    op.alter_column('credit_product_compliance_metadata', 'jurisdiction',
               existing_type=sa.Enum('INDIA', 'USA', 'UK', 'CANADA', 'AUSTRALIA', 'UAE', 'PAKISTAN', 'MYANMAR', 'SYRIA', 'YEMEN', 'AFGHANISTAN', 'SOMALIA', 'SUDAN', 'SOUTH_SUDAN', 'LIBYA', 'LEBANON', 'IRAQ', 'ZIMBABWE', 'VENEZUELA', 'CONGO', 'NORTH_KOREA', 'IRAN', name='country', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)
    op.create_table('fraud_flags',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('card_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rule', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('flagged_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], name=op.f('fraud_flags_card_id_fkey')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fraud_flags_transaction_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('fraud_flags_pkey'))
    )
    op.drop_index(op.f('ix_transaction_idempotency_fingerprint'), table_name='transaction_idempotency')
    op.drop_index('ix_idemp_fingerprint_created', table_name='transaction_idempotency')
    op.drop_table('transaction_idempotency')
    op.drop_index('ix_velocity_card_window', table_name='card_velocity')
    op.drop_index(op.f('ix_card_velocity_card_id'), table_name='card_velocity')
    op.drop_table('card_velocity')
    op.drop_index(op.f('ix_token_blacklist_jti'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_index(op.f('ix_prohibited_countries_country_code'), table_name='prohibited_countries')
    op.drop_table('prohibited_countries')
    # ### end Alembic commands ###
