"""Add bank grade constraints

Revision ID: a29f7d3ffc7e
Revises: 49d94bae5339
Create Date: 2026-03-12 11:36:48.156748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a29f7d3ffc7e'
down_revision: Union[str, Sequence[str], None] = '49d94bae5339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('card_product_id', sa.UUID(), nullable=False))
    op.add_column('card', sa.Column('activation_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('card', sa.Column('international_usage_enabled', sa.Boolean(), nullable=True))
    op.add_column('card', sa.Column('ecommerce_enabled', sa.Boolean(), nullable=True))
    op.add_column('card', sa.Column('atm_enabled', sa.Boolean(), nullable=True))
    op.alter_column('card', 'card_status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('INACTIVE', 'ACTIVE', 'BLOCKED', 'EXPIRED', name='cardstatus', native_enum=False),
               existing_nullable=True)
    op.create_foreign_key(None, 'card', 'card_product_core', ['card_product_id'], ['id'])
    op.drop_index(op.f('ix_card_product_core_code'), table_name='card_product_core')
    op.drop_column('card_product_core', 'code')
    op.add_column('credit_account', sa.Column('credit_limit', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('credit_account', sa.Column('cash_advance_limit', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('credit_account', sa.Column('billing_cycle_id', sa.String(), nullable=False))
    op.add_column('credit_account', sa.Column('internal_risk_rating', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='internalriskrating', native_enum=False), nullable=True))
    op.add_column('credit_account', sa.Column('aml_risk_category', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'EXTREME', name='amlriskcategory', native_enum=False), nullable=True))
    op.add_column('credit_account', sa.Column('overlimit_allowed', sa.Boolean(), nullable=True))
    op.add_column('credit_account', sa.Column('overlimit_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('credit_account', sa.Column('revolving_credit_enabled', sa.Boolean(), nullable=True))
    op.add_column('credit_account', sa.Column('autopay_enabled', sa.Boolean(), nullable=True))
    op.add_column('credit_account', sa.Column('autopay_type', sa.Enum('FULL', 'MINIMUM', name='autopaytype', native_enum=False), nullable=True))
    op.drop_column('credit_account', 'sanctioned_limit')
    op.drop_column('credit_product_information', 'product_sub_category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_product_information', sa.Column('product_sub_category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('credit_account', sa.Column('sanctioned_limit', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.drop_column('credit_account', 'autopay_type')
    op.drop_column('credit_account', 'autopay_enabled')
    op.drop_column('credit_account', 'revolving_credit_enabled')
    op.drop_column('credit_account', 'overlimit_percentage')
    op.drop_column('credit_account', 'overlimit_allowed')
    op.drop_column('credit_account', 'aml_risk_category')
    op.drop_column('credit_account', 'internal_risk_rating')
    op.drop_column('credit_account', 'billing_cycle_id')
    op.drop_column('credit_account', 'cash_advance_limit')
    op.drop_column('credit_account', 'credit_limit')
    op.add_column('card_product_core', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_card_product_core_code'), 'card_product_core', ['code'], unique=True)
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.alter_column('card', 'card_status',
               existing_type=sa.Enum('INACTIVE', 'ACTIVE', 'BLOCKED', 'EXPIRED', name='cardstatus', native_enum=False),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)
    op.drop_column('card', 'atm_enabled')
    op.drop_column('card', 'ecommerce_enabled')
    op.drop_column('card', 'international_usage_enabled')
    op.drop_column('card', 'activation_date')
    op.drop_column('card', 'card_product_id')
    # ### end Alembic commands ###
