"""add linkage_id to otp_codes

Revision ID: a674c72d30b5
Revises: c3f60a962ee3
Create Date: 2026-03-17 15:22:55.690016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a674c72d30b5'
down_revision: Union[str, Sequence[str], None] = 'c3f60a962ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ccm_card_transactions', 'transaction_type',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('PURCHASE', 'REFUND', 'PAYMENT', 'FEE', 'INTEREST', 'CASH_ADVANCE', 'REVERSAL', name='ccmtransactiontype', native_enum=False),
               existing_nullable=False)
    op.alter_column('ccm_card_transactions', 'status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REVERSED', 'AUTHORIZED', name='ccmtransactionstatus', native_enum=False),
               existing_nullable=True)
    op.alter_column('ccm_credit_accounts', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('otp_codes', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('otp_codes', sa.Column('linkage_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp_codes', 'linkage_id')
    op.drop_column('otp_codes', 'is_verified')
    op.alter_column('ccm_credit_accounts', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('ccm_card_transactions', 'status',
               existing_type=sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REVERSED', 'AUTHORIZED', name='ccmtransactionstatus', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)
    op.alter_column('ccm_card_transactions', 'transaction_type',
               existing_type=sa.Enum('PURCHASE', 'REFUND', 'PAYMENT', 'FEE', 'INTEREST', 'CASH_ADVANCE', 'REVERSAL', name='ccmtransactiontype', native_enum=False),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###
