"""drop_admin_suffix_position

Revision ID: b87bba2dff98
Revises: 89550b9c8641
Create Date: 2026-04-01 16:14:22.875300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b87bba2dff98'
down_revision: Union[str, Sequence[str], None] = '89550b9c8641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'position')
    op.drop_column('admins', 'suffix')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('suffix', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('admins', sa.Column('position', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
