"""add is_cif_completed to users

Revision ID: ef34d096df09
Revises: 14c3fcced61d
Create Date: 2026-02-26 12:49:23.523366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef34d096df09'
down_revision: Union[str, Sequence[str], None] = '14c3fcced61d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_cif_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_cif_completed')
    # ### end Alembic commands ###
