"""add_transaction_processing_tables

Revision ID: 89550b9c8641
Revises: trans_bill_001
Create Date: 2026-03-24 14:46:02.916204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89550b9c8641'
down_revision: Union[str, Sequence[str], None] = 'trans_bill_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clearing_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('network', sa.String(length=20), nullable=False),
    sa.Column('file_reference', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.Column('exception_count', sa.Integer(), nullable=False),
    sa.Column('force_post_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settlement_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('network', sa.String(length=20), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cards_settled', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.String(length=50), nullable=True),
    sa.Column('actor_role', sa.String(length=20), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'transaction_audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_transaction_audit_log_entity_id'), 'transaction_audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_transaction_audit_log_timestamp'), 'transaction_audit_log', ['timestamp'], unique=False)
    op.create_table('card_controls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('international_transactions_enabled', sa.Boolean(), nullable=False),
    sa.Column('online_transactions_enabled', sa.Boolean(), nullable=False),
    sa.Column('contactless_enabled', sa.Boolean(), nullable=False),
    sa.Column('atm_withdrawals_enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_limit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('single_transaction_limit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('monthly_limit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('mcc_blocks', sa.JSON(), nullable=True),
    sa.Column('allowed_countries', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_controls_card_id'), 'card_controls', ['card_id'], unique=True)
    op.create_table('card_controls_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('previous_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('diff', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_controls_history_card_id'), 'card_controls_history', ['card_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('payment_source', sa.String(length=20), nullable=False),
    sa.Column('source_reference', sa.String(length=100), nullable=False),
    sa.Column('allocation_breakdown', sa.JSON(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_card_status', 'payments', ['card_id', 'status'], unique=False)
    op.create_index(op.f('ix_payments_card_id'), 'payments', ['card_id'], unique=False)
    op.create_table('provisional_credits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dispute_id', sa.UUID(), nullable=True),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provisional_credits_card_id'), 'provisional_credits', ['card_id'], unique=False)
    op.create_index(op.f('ix_provisional_credits_dispute_id'), 'provisional_credits', ['dispute_id'], unique=False)
    op.create_table('statements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('cycle_start', sa.Date(), nullable=False),
    sa.Column('cycle_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_purchases', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_cash_advances', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_fees', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_credits', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('minimum_due', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_due_date', sa.Date(), nullable=True),
    sa.Column('fully_paid', sa.Boolean(), nullable=False),
    sa.Column('min_paid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_statement_card_cycle', 'statements', ['card_id', 'cycle_start', 'cycle_end'], unique=False)
    op.create_index(op.f('ix_statements_card_id'), 'statements', ['card_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('merchant_name', sa.String(length=255), nullable=True),
    sa.Column('merchant_category_code', sa.String(length=4), nullable=True),
    sa.Column('merchant_country', sa.String(length=2), nullable=True),
    sa.Column('auth_code', sa.String(length=8), nullable=True),
    sa.Column('terminal_id', sa.String(length=50), nullable=True),
    sa.Column('pos_entry_mode', sa.String(length=10), nullable=True),
    sa.Column('card_not_present', sa.Boolean(), nullable=False),
    sa.Column('installments', sa.Integer(), nullable=True),
    sa.Column('parent_txn_id', sa.UUID(), nullable=True),
    sa.Column('fraud_score', sa.Float(), nullable=True),
    sa.Column('risk_tier', sa.String(length=20), nullable=True),
    sa.Column('internal_flag', sa.Boolean(), nullable=False),
    sa.Column('internal_flag_reason', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['credit_account.id'], ),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['parent_txn_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_auth_code'), 'transactions', ['auth_code'], unique=True)
    op.create_index(op.f('ix_transactions_card_id'), 'transactions', ['card_id'], unique=False)
    op.create_index(op.f('ix_transactions_idempotency_key'), 'transactions', ['idempotency_key'], unique=True)
    op.create_index('ix_txn_card_created', 'transactions', ['card_id', 'created_at'], unique=False)
    op.create_index('ix_txn_merchant', 'transactions', ['merchant_id'], unique=False)
    op.create_index('ix_txn_status', 'transactions', ['status'], unique=False)
    op.create_table('clearing_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('clearing_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('interchange_fee', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('network_fee', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('clearing_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('force_post', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['clearing_batches.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clearing_records_batch_id'), 'clearing_records', ['batch_id'], unique=False)
    op.create_index(op.f('ix_clearing_records_transaction_id'), 'clearing_records', ['transaction_id'], unique=False)
    op.create_table('credit_holds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('hold_expiry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('release_reason', sa.Text(), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_holds_card_id'), 'credit_holds', ['card_id'], unique=False)
    op.create_index(op.f('ix_credit_holds_transaction_id'), 'credit_holds', ['transaction_id'], unique=False)
    op.create_index('ix_hold_card_status', 'credit_holds', ['card_id', 'status'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('case_number', sa.String(length=20), nullable=False),
    sa.Column('dispute_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount_disputed', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provisional_credit_id', sa.UUID(), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['provisional_credit_id'], ['provisional_credits.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dispute_card_status', 'disputes', ['card_id', 'status'], unique=False)
    op.create_index(op.f('ix_disputes_card_id'), 'disputes', ['card_id'], unique=False)
    op.create_index(op.f('ix_disputes_case_number'), 'disputes', ['case_number'], unique=True)
    op.create_index(op.f('ix_disputes_transaction_id'), 'disputes', ['transaction_id'], unique=False)
    op.create_table('fees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('fee_type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('waived', sa.Boolean(), nullable=False),
    sa.Column('waiver_reason', sa.Text(), nullable=True),
    sa.Column('waived_by', sa.String(length=100), nullable=True),
    sa.Column('linked_transaction_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['linked_transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fee_card_type', 'fees', ['card_id', 'fee_type'], unique=False)
    op.create_index(op.f('ix_fees_card_id'), 'fees', ['card_id'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_txn_id', sa.UUID(), nullable=False),
    sa.Column('refund_txn_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('merchant_reference', sa.String(length=100), nullable=True),
    sa.Column('partial', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['original_txn_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['refund_txn_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_original_txn_id'), 'refunds', ['original_txn_id'], unique=False)
    op.create_index(op.f('ix_refunds_refund_txn_id'), 'refunds', ['refund_txn_id'], unique=False)
    op.create_table('risk_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('risk_tier', sa.String(length=20), nullable=False),
    sa.Column('fraud_score', sa.Float(), nullable=False),
    sa.Column('rules_triggered', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('review_outcome', sa.String(length=20), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_alert_status', 'risk_alerts', ['status'], unique=False)
    op.create_index('ix_risk_alert_tier', 'risk_alerts', ['risk_tier'], unique=False)
    op.create_index(op.f('ix_risk_alerts_card_id'), 'risk_alerts', ['card_id'], unique=False)
    op.create_index(op.f('ix_risk_alerts_transaction_id'), 'risk_alerts', ['transaction_id'], unique=False)
    op.create_table('settlement_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('settlement_run_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('interchange_earned', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['settlement_run_id'], ['settlement_runs.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlement_records_settlement_run_id'), 'settlement_records', ['settlement_run_id'], unique=False)
    op.create_index(op.f('ix_settlement_records_transaction_id'), 'settlement_records', ['transaction_id'], unique=False)
    op.create_table('statement_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('statement_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('line_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('line_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statement_line_items_statement_id'), 'statement_line_items', ['statement_id'], unique=False)
    op.create_table('dispute_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dispute_id', sa.UUID(), nullable=False),
    sa.Column('submitted_by', sa.String(length=100), nullable=False),
    sa.Column('document_s3_key', sa.String(length=500), nullable=True),
    sa.Column('statement', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispute_evidence_dispute_id'), 'dispute_evidence', ['dispute_id'], unique=False)
    # --- UUID→VARCHAR migration: drop ALL FKs on users.id first ---
    op.drop_constraint('auth_credentials_user_id_fkey', 'auth_credentials', type_='foreignkey')
    op.execute("ALTER TABLE otp_codes DROP CONSTRAINT IF EXISTS otp_codes_user_id_fkey")
    op.execute("ALTER TABLE customer_profiles DROP CONSTRAINT IF EXISTS customer_profiles_user_id_fkey")
    op.execute("ALTER TABLE ccm_credit_accounts DROP CONSTRAINT IF EXISTS ccm_credit_accounts_user_id_fkey")
    op.execute("ALTER TABLE ccm_credit_cards DROP CONSTRAINT IF EXISTS ccm_credit_cards_user_id_fkey")
    op.execute("ALTER TABLE credit_account DROP CONSTRAINT IF EXISTS credit_account_user_id_fkey")
    op.execute("ALTER TABLE credit_card_application DROP CONSTRAINT IF EXISTS credit_card_application_user_id_fkey")

    # Change users.id PK first (the referenced column)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=20),
               existing_nullable=False,
               postgresql_using="id::varchar")

    # Now change all referencing columns
    op.alter_column('auth_credentials', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=20),
               nullable=False,
               postgresql_using="user_id::varchar")
    op.alter_column('auth_credentials', 'password_updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('ccm_card_transactions', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.add_column('ccm_card_transactions', sa.Column('reference_id', sa.String(), nullable=True))
    op.add_column('ccm_card_transactions', sa.Column('settlement_date', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('ccm_card_transactions', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ccm_card_transactions', 'status',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('ccm_card_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(None, 'ccm_card_transactions', ['idempotency_key'])
    op.drop_column('ccm_card_transactions', 'is_fraud_flagged')
    op.drop_column('ccm_card_transactions', 'geo_location')
    op.alter_column('ccm_credit_account_adjustments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ccm_credit_account_ledger', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('ccm_credit_accounts', sa.Column('version', sa.Integer(), nullable=False))
    op.alter_column('ccm_credit_accounts', 'outstanding_balance',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('ccm_credit_accounts', 'billing_cycle_day',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ccm_credit_accounts', 'payment_due_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('20'))
    op.alter_column('ccm_credit_accounts', 'minimum_due',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('ccm_credit_accounts', 'interest_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('ccm_credit_accounts', 'late_fee',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('ccm_credit_accounts', 'purchase_apr',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('3.49'))
    op.alter_column('ccm_credit_accounts', 'cash_apr',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('3.99'))
    op.alter_column('ccm_credit_accounts', 'penalty_apr',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('4.99'))
    op.alter_column('ccm_credit_accounts', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ccm_credit_accounts', 'risk_flag',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'NONE'::character varying"))
    op.alter_column('ccm_credit_accounts', 'overlimit_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('ccm_credit_accounts', 'overlimit_buffer',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('ccm_credit_accounts', 'overlimit_fee',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('ccm_credit_accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ccm_credit_cards', 'status',
               existing_type=sa.VARCHAR(length=13),
               nullable=False)
    op.alter_column('ccm_credit_cards', 'is_virtual',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('ccm_credit_cards', 'is_contactless_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('ccm_credit_cards', 'is_international_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('ccm_credit_cards', 'is_online_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('ccm_credit_cards', 'is_atm_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('ccm_credit_cards', 'is_domestic_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('ccm_credit_cards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('credit_account', sa.Column('user_id', sa.String(length=20), nullable=False))
    op.drop_constraint(op.f('credit_account_cif_id_fkey'), 'credit_account', type_='foreignkey')
    op.create_foreign_key(None, 'credit_account', 'users', ['user_id'], ['id'])
    op.drop_column('credit_account', 'cif_id')
    op.alter_column('credit_card_application', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=20),
               existing_nullable=False,
               postgresql_using="user_id::varchar")
    op.drop_constraint(op.f('credit_card_application_cif_id_fkey'), 'credit_card_application', type_='foreignkey')
    op.drop_column('credit_card_application', 'cif_id')
    op.alter_column('customer_addresses', 'customer_profile_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('customer_addresses', 'address_type',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    op.alter_column('customer_addresses', 'same_as_current',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('customer_addresses', 'is_kyc_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('customer_addresses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('customer_profiles', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=20),
               nullable=False,
               postgresql_using="user_id::varchar")
    # Re-create customer_profiles FK after both columns are varchar
    op.create_foreign_key('customer_profiles_user_id_fkey', 'customer_profiles', 'users', ['user_id'], ['id'])
    op.alter_column('customer_profiles', 'dual_citizenship',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('customer_profiles', 'preferred_language',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)
    op.alter_column('customer_profiles', 'kyc_state',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    op.alter_column('customer_profiles', 'primary_jurisdiction',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    op.alter_column('customer_profiles', 'customer_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customer_profiles', 'pep_flag',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('customer_profiles', 'high_risk_flag',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('customer_profiles', 'fatca_required',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('customer_profiles', 'kyc_reupload_requested',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('customer_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_customer_profiles_cif_number'), table_name='customer_profiles')
    op.drop_column('customer_profiles', 'cif_number')
    op.alter_column('employment_details', 'customer_profile_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('employment_details', 'employment_type',
               existing_type=sa.VARCHAR(length=13),
               nullable=False)
    op.alter_column('employment_details', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('fatca_declarations', 'customer_profile_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('fatca_declarations', 'us_citizen',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('fatca_declarations', 'us_tax_resident',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('fatca_declarations', 'declaration_signed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('financial_information', 'customer_profile_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('financial_information', 'bankruptcy_flag',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('financial_information', 'default_history_flag',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('financial_information', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('kyc_document_submissions', 'kyc_profile_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('kyc_document_submissions', 'verification_status',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    op.alter_column('kyc_document_submissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('kyc_otp_verifications', 'document_submission_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('kyc_otp_verifications', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('kyc_otp_verifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('otp_codes', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=20),
               existing_nullable=True,
               postgresql_using="user_id::varchar")
    # Re-create otp_codes FK after both columns are varchar
    op.create_foreign_key('otp_codes_user_id_fkey', 'otp_codes', 'users', ['user_id'], ['id'])
    op.alter_column('otp_codes', 'is_used',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('otp_codes', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('otp_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('pending_registrations', 'suffix')
    op.alter_column('risk_compliance_logs', 'kyc_profile_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('risk_compliance_logs', 'status',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('risk_compliance_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # Re-create auth_credentials FK after both columns are varchar
    op.create_foreign_key('auth_credentials_user_id_fkey', 'auth_credentials', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_cif_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_kyc_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_kyc_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_cif_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.String(length=20),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('risk_compliance_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('risk_compliance_logs', 'status',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('risk_compliance_logs', 'kyc_profile_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('pending_registrations', sa.Column('suffix', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('otp_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('otp_codes', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('otp_codes', 'is_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('otp_codes', 'user_id',
               existing_type=sa.String(length=20),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('kyc_otp_verifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('kyc_otp_verifications', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('kyc_otp_verifications', 'document_submission_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('kyc_document_submissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('kyc_document_submissions', 'verification_status',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.alter_column('kyc_document_submissions', 'kyc_profile_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('financial_information', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('financial_information', 'default_history_flag',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('financial_information', 'bankruptcy_flag',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('financial_information', 'customer_profile_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('fatca_declarations', 'declaration_signed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('fatca_declarations', 'us_tax_resident',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('fatca_declarations', 'us_citizen',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('fatca_declarations', 'customer_profile_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('employment_details', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('employment_details', 'employment_type',
               existing_type=sa.VARCHAR(length=13),
               nullable=True)
    op.alter_column('employment_details', 'customer_profile_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('customer_profiles', sa.Column('cif_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_customer_profiles_cif_number'), 'customer_profiles', ['cif_number'], unique=True)
    op.alter_column('customer_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('customer_profiles', 'kyc_reupload_requested',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('customer_profiles', 'fatca_required',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('customer_profiles', 'high_risk_flag',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('customer_profiles', 'pep_flag',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('customer_profiles', 'customer_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customer_profiles', 'primary_jurisdiction',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    op.alter_column('customer_profiles', 'kyc_state',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    op.alter_column('customer_profiles', 'preferred_language',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)
    op.alter_column('customer_profiles', 'dual_citizenship',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('customer_profiles', 'user_id',
               existing_type=sa.String(length=20),
               type_=sa.UUID(),
               nullable=True)
    op.alter_column('customer_addresses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('customer_addresses', 'is_kyc_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('customer_addresses', 'same_as_current',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('customer_addresses', 'address_type',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    op.alter_column('customer_addresses', 'customer_profile_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('credit_card_application', sa.Column('cif_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('credit_card_application_cif_id_fkey'), 'credit_card_application', 'customer_profiles', ['cif_id'], ['id'])
    op.alter_column('credit_card_application', 'user_id',
               existing_type=sa.String(length=20),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('credit_account', sa.Column('cif_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'credit_account', type_='foreignkey')
    op.create_foreign_key(op.f('credit_account_cif_id_fkey'), 'credit_account', 'customer_profiles', ['cif_id'], ['id'])
    op.drop_column('credit_account', 'user_id')
    op.alter_column('ccm_credit_cards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ccm_credit_cards', 'is_domestic_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('ccm_credit_cards', 'is_atm_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('ccm_credit_cards', 'is_online_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('ccm_credit_cards', 'is_international_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('ccm_credit_cards', 'is_contactless_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('ccm_credit_cards', 'is_virtual',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('ccm_credit_cards', 'status',
               existing_type=sa.VARCHAR(length=13),
               nullable=True)
    op.alter_column('ccm_credit_accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ccm_credit_accounts', 'overlimit_fee',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('ccm_credit_accounts', 'overlimit_buffer',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('ccm_credit_accounts', 'overlimit_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('ccm_credit_accounts', 'risk_flag',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'NONE'::character varying"))
    op.alter_column('ccm_credit_accounts', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ccm_credit_accounts', 'penalty_apr',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('4.99'))
    op.alter_column('ccm_credit_accounts', 'cash_apr',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('3.99'))
    op.alter_column('ccm_credit_accounts', 'purchase_apr',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('3.49'))
    op.alter_column('ccm_credit_accounts', 'late_fee',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('ccm_credit_accounts', 'interest_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('ccm_credit_accounts', 'minimum_due',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('ccm_credit_accounts', 'payment_due_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('20'))
    op.alter_column('ccm_credit_accounts', 'billing_cycle_day',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ccm_credit_accounts', 'outstanding_balance',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.drop_column('ccm_credit_accounts', 'version')
    op.alter_column('ccm_credit_account_ledger', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ccm_credit_account_adjustments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('ccm_card_transactions', sa.Column('geo_location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ccm_card_transactions', sa.Column('is_fraud_flagged', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ccm_card_transactions', type_='unique')
    op.alter_column('ccm_card_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ccm_card_transactions', 'status',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('ccm_card_transactions', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('ccm_card_transactions', 'settlement_date')
    op.drop_column('ccm_card_transactions', 'reference_id')
    op.drop_column('ccm_card_transactions', 'idempotency_key')
    op.alter_column('auth_credentials', 'password_updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('auth_credentials', 'user_id',
               existing_type=sa.String(length=20),
               type_=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_dispute_evidence_dispute_id'), table_name='dispute_evidence')
    op.drop_table('dispute_evidence')
    op.drop_index(op.f('ix_statement_line_items_statement_id'), table_name='statement_line_items')
    op.drop_table('statement_line_items')
    op.drop_index(op.f('ix_settlement_records_transaction_id'), table_name='settlement_records')
    op.drop_index(op.f('ix_settlement_records_settlement_run_id'), table_name='settlement_records')
    op.drop_table('settlement_records')
    op.drop_index(op.f('ix_risk_alerts_transaction_id'), table_name='risk_alerts')
    op.drop_index(op.f('ix_risk_alerts_card_id'), table_name='risk_alerts')
    op.drop_index('ix_risk_alert_tier', table_name='risk_alerts')
    op.drop_index('ix_risk_alert_status', table_name='risk_alerts')
    op.drop_table('risk_alerts')
    op.drop_index(op.f('ix_refunds_refund_txn_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_original_txn_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_fees_card_id'), table_name='fees')
    op.drop_index('ix_fee_card_type', table_name='fees')
    op.drop_table('fees')
    op.drop_index(op.f('ix_disputes_transaction_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_case_number'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_card_id'), table_name='disputes')
    op.drop_index('ix_dispute_card_status', table_name='disputes')
    op.drop_table('disputes')
    op.drop_index('ix_hold_card_status', table_name='credit_holds')
    op.drop_index(op.f('ix_credit_holds_transaction_id'), table_name='credit_holds')
    op.drop_index(op.f('ix_credit_holds_card_id'), table_name='credit_holds')
    op.drop_table('credit_holds')
    op.drop_index(op.f('ix_clearing_records_transaction_id'), table_name='clearing_records')
    op.drop_index(op.f('ix_clearing_records_batch_id'), table_name='clearing_records')
    op.drop_table('clearing_records')
    op.drop_index('ix_txn_status', table_name='transactions')
    op.drop_index('ix_txn_merchant', table_name='transactions')
    op.drop_index('ix_txn_card_created', table_name='transactions')
    op.drop_index(op.f('ix_transactions_idempotency_key'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_card_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_auth_code'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_statements_card_id'), table_name='statements')
    op.drop_index('ix_statement_card_cycle', table_name='statements')
    op.drop_table('statements')
    op.drop_index(op.f('ix_provisional_credits_dispute_id'), table_name='provisional_credits')
    op.drop_index(op.f('ix_provisional_credits_card_id'), table_name='provisional_credits')
    op.drop_table('provisional_credits')
    op.drop_index(op.f('ix_payments_card_id'), table_name='payments')
    op.drop_index('ix_payment_card_status', table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_card_controls_history_card_id'), table_name='card_controls_history')
    op.drop_table('card_controls_history')
    op.drop_index(op.f('ix_card_controls_card_id'), table_name='card_controls')
    op.drop_table('card_controls')
    op.drop_index(op.f('ix_transaction_audit_log_timestamp'), table_name='transaction_audit_log')
    op.drop_index(op.f('ix_transaction_audit_log_entity_id'), table_name='transaction_audit_log')
    op.drop_index('ix_audit_entity', table_name='transaction_audit_log')
    op.drop_table('transaction_audit_log')
    op.drop_table('settlement_runs')
    op.drop_table('clearing_batches')
    # ### end Alembic commands ###
