"""Refactor AddressSchema to Array

Revision ID: 525b01bd97ca
Revises: eea5a8e8cad4
Create Date: 2026-02-27 19:20:00.243180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '525b01bd97ca'
down_revision: Union[str, Sequence[str], None] = 'eea5a8e8cad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_addresses', sa.Column('address_type', sa.Enum('CURRENT', 'PERMANENT', 'OFFICE', 'PREVIOUS', name='addresstype', native_enum=False), nullable=True))
    op.add_column('customer_addresses', sa.Column('same_as_current', sa.Boolean(), nullable=True))
    op.add_column('customer_addresses', sa.Column('is_kyc_verified', sa.Boolean(), nullable=True))
    op.alter_column('customer_addresses', 'address_line_1',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('customer_addresses', 'is_current')
    op.drop_column('customer_addresses', 'residence_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_addresses', sa.Column('residence_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customer_addresses', sa.Column('is_current', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('customer_addresses', 'address_line_1',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('customer_addresses', 'is_kyc_verified')
    op.drop_column('customer_addresses', 'same_as_current')
    op.drop_column('customer_addresses', 'address_type')
    # ### end Alembic commands ###
