"""Increase interest rate precision for larger percentages

Revision ID: 75f26e65dd5c
Revises: 89f11f69a390
Create Date: 2026-03-03 12:22:48.221342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75f26e65dd5c'
down_revision: Union[str, Sequence[str], None] = '89f11f69a390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credit_product_interest_framework', 'base_interest_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('credit_product_interest_framework', 'penal_interest_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credit_product_interest_framework', 'penal_interest_rate',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('credit_product_interest_framework', 'base_interest_rate',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###
