"""Add residence_type, years_at_address, and address_line_2

Revision ID: 7d6db55f4dbc
Revises: 525b01bd97ca
Create Date: 2026-02-28 14:53:08.067470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d6db55f4dbc'
down_revision: Union[str, Sequence[str], None] = '525b01bd97ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_addresses', sa.Column('residence_type', sa.Enum('OWNED', 'MORTGAGED', 'RENTED', 'LIVING_WITH_PARENTS', name='residencetype', native_enum=False), nullable=True))
    op.alter_column('customer_addresses', 'address_type',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('CURRENT', 'PERMANENT', 'OFFICE', 'PREVIOUS', 'ALTERNATIVE', name='addresstype', native_enum=False),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_addresses', 'address_type',
               existing_type=sa.Enum('CURRENT', 'PERMANENT', 'OFFICE', 'PREVIOUS', 'ALTERNATIVE', name='addresstype', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)
    op.drop_column('customer_addresses', 'residence_type')
    # ### end Alembic commands ###
