"""Refactor CustomerProfile columns

Revision ID: eea5a8e8cad4
Revises: f1c9928669f3
Create Date: 2026-02-27 18:28:17.477397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eea5a8e8cad4'
down_revision: Union[str, Sequence[str], None] = 'f1c9928669f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_profiles', sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender', native_enum=False), nullable=True))
    op.add_column('customer_profiles', sa.Column('marital_status', sa.Enum('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', name='maritalstatus', native_enum=False), nullable=True))
    op.add_column('customer_profiles', sa.Column('preferred_language', sa.Enum('ENGLISH', 'SPANISH', 'FRENCH', 'HINDI', name='preferredlanguage', native_enum=False), nullable=True))
    op.drop_column('customer_profiles', 'citizenship_number_hash')
    op.drop_column('customer_profiles', 'primary_mobile_number')
    op.drop_column('customer_profiles', 'citizenship_document_type')
    op.drop_column('customer_profiles', 'timezone')
    op.drop_column('customer_profiles', 'alternate_mobile_number')
    op.drop_column('customer_profiles', 'terms_accepted_at')
    op.drop_column('customer_profiles', 'terms_ip_address')
    op.drop_column('customer_profiles', 'primary_mobile_country_code')
    op.drop_column('customer_profiles', 'terms_user_agent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_profiles', sa.Column('terms_user_agent', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customer_profiles', sa.Column('primary_mobile_country_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customer_profiles', sa.Column('terms_ip_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customer_profiles', sa.Column('terms_accepted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('customer_profiles', sa.Column('alternate_mobile_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customer_profiles', sa.Column('timezone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customer_profiles', sa.Column('citizenship_document_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customer_profiles', sa.Column('primary_mobile_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customer_profiles', sa.Column('citizenship_number_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('customer_profiles', 'preferred_language')
    op.drop_column('customer_profiles', 'marital_status')
    op.drop_column('customer_profiles', 'gender')
    # ### end Alembic commands ###
