"""multi-country kyc

Revision ID: f16ca6ef7f52
Revises: 7d6db55f4dbc
Create Date: 2026-03-01 01:14:49.228613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f16ca6ef7f52'
down_revision: Union[str, Sequence[str], None] = '7d6db55f4dbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kyc_document_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kyc_profile_id', sa.UUID(), nullable=True),
    sa.Column('document_category', sa.Enum('IDENTITY_PROOF', 'ADDRESS_PROOF', name='documentcategory', native_enum=False), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('document_reference_masked', sa.String(), nullable=True),
    sa.Column('document_reference_token', sa.String(), nullable=True),
    sa.Column('s3_file_locator', sa.String(), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='kycverificationstatus', native_enum=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['kyc_profile_id'], ['customer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_compliance_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kyc_profile_id', sa.UUID(), nullable=True),
    sa.Column('screening_type', sa.Enum('AML', 'SANCTIONS', 'PEP', 'ADVERSE_MEDIA', name='screeningtype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('CLEARED', 'REVIEW_REQUIRED', 'FAILED', name='screeningstatus', native_enum=False), nullable=True),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('system_remarks', sa.String(), nullable=True),
    sa.Column('audited_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['kyc_profile_id'], ['customer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kyc_otp_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_submission_id', sa.UUID(), nullable=True),
    sa.Column('phone_number_masked', sa.String(), nullable=True),
    sa.Column('otp_hash', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_submission_id'], ['kyc_document_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('kyc_records')
    op.add_column('customer_profiles', sa.Column('kyc_state', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'PARTIAL', 'COMPLETED', 'FAILED', 'EXPIRED', name='kycstate', native_enum=False), nullable=True))
    op.add_column('customer_profiles', sa.Column('primary_jurisdiction', sa.Enum('INDIA', 'US', 'UK', 'UAE', 'AUSTRALIA', name='primaryjurisdiction', native_enum=False), nullable=True))
    op.drop_column('customer_profiles', 'kyc_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_profiles', sa.Column('kyc_status', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('customer_profiles', 'primary_jurisdiction')
    op.drop_column('customer_profiles', 'kyc_state')
    op.create_table('kyc_records',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('customer_profile_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('document_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('document_number_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('document_file_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('verified_status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_profile_id'], ['customer_profiles.id'], name=op.f('kyc_records_customer_profile_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('kyc_records_pkey'))
    )
    op.drop_table('kyc_otp_verifications')
    op.drop_table('risk_compliance_logs')
    op.drop_table('kyc_document_submissions')
    # ### end Alembic commands ###
