"""add contact to admin

Revision ID: f50f53ff89d5
Revises: 6011f54b952f
Create Date: 2026-03-02 09:58:32.727137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f50f53ff89d5'
down_revision: Union[str, Sequence[str], None] = '6011f54b952f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('contact', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'admins', ['contact'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admins', type_='unique')
    op.drop_column('admins', 'contact')
    # ### end Alembic commands ###
