"""enterprise_credit_card_schema

Revision ID: 0d66cefbc956
Revises: 3c3e8e6d0808
Create Date: 2026-03-01 17:59:17.844465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d66cefbc956'
down_revision: Union[str, Sequence[str], None] = '3c3e8e6d0808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_product_information',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_code', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('product_category', sa.Enum('CARD', 'LOAN', name='productcategory', native_enum=False), nullable=True),
    sa.Column('product_sub_category', sa.String(), nullable=True),
    sa.Column('product_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'SUSPENDED', 'CLOSED', name='productstatus', native_enum=False), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_product_information_product_code'), 'credit_product_information', ['product_code'], unique=True)
    op.create_table('card_product_core',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('credit_product_id', sa.UUID(), nullable=False),
    sa.Column('card_network', sa.Enum('VISA', 'MASTERCARD', 'RUPAY', 'AMEX', name='cardnetwork', native_enum=False), nullable=False),
    sa.Column('card_bin_range', sa.String(), nullable=False),
    sa.Column('card_branding_code', sa.String(), nullable=False),
    sa.Column('card_form_factor', sa.Enum('PHYSICAL', 'VIRTUAL', 'HYBRID', name='cardformfactor', native_enum=False), nullable=True),
    sa.Column('card_variant', sa.Enum('CLASSIC', 'GOLD', 'PLATINUM', 'SIGNATURE', 'INFINITE', name='cardvariant', native_enum=False), nullable=True),
    sa.Column('default_card_currency', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['credit_product_id'], ['credit_product_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_product_accounting_mapping',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('credit_product_id', sa.UUID(), nullable=False),
    sa.Column('principal_gl_code', sa.String(), nullable=False),
    sa.Column('interest_income_gl_code', sa.String(), nullable=False),
    sa.Column('fee_income_gl_code', sa.String(), nullable=False),
    sa.Column('penalty_gl_code', sa.String(), nullable=False),
    sa.Column('writeoff_gl_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['credit_product_id'], ['credit_product_information.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credit_product_id')
    )
    op.create_table('credit_product_compliance_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('credit_product_id', sa.UUID(), nullable=False),
    sa.Column('regulatory_product_code', sa.String(), nullable=False),
    sa.Column('kyc_level_required', sa.String(), nullable=True),
    sa.Column('aml_risk_category', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'EXTREME', name='amlriskcategory', native_enum=False), nullable=True),
    sa.Column('jurisdiction', sa.Enum('INDIA', 'USA', 'UK', 'CANADA', 'AUSTRALIA', 'UAE', name='country', native_enum=False), nullable=True),
    sa.Column('tax_applicability', sa.Enum('GST_APPLICABLE', 'NOT_APPLICABLE', name='taxapplicability', native_enum=False), nullable=True),
    sa.Column('statement_disclosure_version', sa.String(), nullable=False),
    sa.Column('regulatory_reporting_category', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['credit_product_id'], ['credit_product_information.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credit_product_id')
    )
    op.create_table('credit_product_eligibility_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('credit_product_id', sa.UUID(), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('min_income_required', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('employment_types_allowed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('min_credit_score', sa.Integer(), nullable=True),
    sa.Column('secured_flag', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['credit_product_id'], ['credit_product_information.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credit_product_id')
    )
    op.create_table('credit_product_fees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('credit_product_id', sa.UUID(), nullable=False),
    sa.Column('joining_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('annual_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('renewal_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('late_payment_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('overlimit_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cash_advance_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('foreign_markup_fee_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['credit_product_id'], ['credit_product_information.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credit_product_id')
    )
    op.create_table('credit_product_governance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('credit_product_id', sa.UUID(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_renewal_allowed', sa.Boolean(), nullable=True),
    sa.Column('cooling_period_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['credit_product_id'], ['credit_product_information.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credit_product_id')
    )
    op.create_table('credit_product_interest_framework',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('credit_product_id', sa.UUID(), nullable=False),
    sa.Column('interest_type', sa.Enum('FIXED', 'FLOATING', name='interesttype', native_enum=False), nullable=True),
    sa.Column('base_interest_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('interest_calculation_method', sa.Enum('AVERAGE_DAILY_BALANCE', 'DAILY_BALANCE', 'ADJUSTED_BALANCE', name='interestcalculationmethod', native_enum=False), nullable=True),
    sa.Column('interest_basis', sa.Enum('ACTUAL_360', 'ACTUAL_365', name='interestbasis', native_enum=False), nullable=True),
    sa.Column('penal_interest_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('interest_free_allowed', sa.Boolean(), nullable=True),
    sa.Column('max_interest_free_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['credit_product_id'], ['credit_product_information.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credit_product_id')
    )
    op.create_table('credit_product_international_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('credit_product_id', sa.UUID(), nullable=False),
    sa.Column('international_txn_allowed', sa.Boolean(), nullable=True),
    sa.Column('supported_currencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fx_rate_source', sa.String(), nullable=True),
    sa.Column('fx_conversion_method', sa.String(), nullable=True),
    sa.Column('cross_border_fee_applicable', sa.Boolean(), nullable=True),
    sa.Column('cross_border_fee_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('international_cash_allowed', sa.Boolean(), nullable=True),
    sa.Column('international_txn_limit_cap', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['credit_product_id'], ['credit_product_information.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credit_product_id')
    )
    op.create_table('credit_product_limits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('credit_product_id', sa.UUID(), nullable=False),
    sa.Column('min_credit_limit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('max_credit_limit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('max_total_exposure_per_cif', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('revolving_credit_allowed', sa.Boolean(), nullable=True),
    sa.Column('overlimit_allowed', sa.Boolean(), nullable=True),
    sa.Column('overlimit_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['credit_product_id'], ['credit_product_information.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credit_product_id')
    )
    op.create_table('card_authorization_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_product_id', sa.UUID(), nullable=False),
    sa.Column('partial_auth_allowed', sa.Boolean(), nullable=True),
    sa.Column('offline_txn_allowed', sa.Boolean(), nullable=True),
    sa.Column('authorization_ttl_seconds', sa.Integer(), nullable=True),
    sa.Column('retry_authorization_allowed', sa.Boolean(), nullable=True),
    sa.Column('network_stand_in_allowed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['card_product_id'], ['card_product_core.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_product_id')
    )
    op.create_table('card_billing_configuration',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_product_id', sa.UUID(), nullable=False),
    sa.Column('billing_cycle_type', sa.Enum('MONTHLY', 'BI_MONTHLY', 'QUARTERLY', name='billingcycletype', native_enum=False), nullable=True),
    sa.Column('billing_cycle_day', sa.Integer(), nullable=True),
    sa.Column('payment_due_days', sa.Integer(), nullable=True),
    sa.Column('minimum_due_formula', sa.String(), nullable=True),
    sa.Column('statement_generation_mode', sa.Enum('ELECTRONIC', 'PHYSICAL', 'BOTH', name='statementgenerationmode', native_enum=False), nullable=True),
    sa.Column('statement_currency', sa.String(), nullable=True),
    sa.Column('grace_period_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_product_id'], ['card_product_core.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_product_id')
    )
    op.create_table('card_fraud_risk_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_product_id', sa.UUID(), nullable=False),
    sa.Column('fraud_monitoring_profile', sa.Enum('STANDARD', 'STRICT', name='fraudmonitoringprofile', native_enum=False), nullable=True),
    sa.Column('velocity_check_profile', sa.Enum('STANDARD', 'AGGRESSIVE', name='velocitycheckprofile', native_enum=False), nullable=True),
    sa.Column('geo_blocking_supported', sa.Boolean(), nullable=True),
    sa.Column('fallback_auth_allowed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['card_product_id'], ['card_product_core.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_product_id')
    )
    op.create_table('card_lifecycle_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_product_id', sa.UUID(), nullable=False),
    sa.Column('card_validity_years', sa.Integer(), nullable=True),
    sa.Column('auto_renew_card', sa.Boolean(), nullable=True),
    sa.Column('replacement_reason_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reissue_fee_applicable', sa.Boolean(), nullable=True),
    sa.Column('temporary_block_supported', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['card_product_id'], ['card_product_core.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_product_id')
    )
    op.create_table('card_product_governance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_product_id', sa.UUID(), nullable=False),
    sa.Column('card_product_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'SUSPENDED', 'CLOSED', name='productstatus', native_enum=False), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['card_product_id'], ['card_product_core.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_product_id')
    )
    op.create_table('card_rewards_configuration',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_product_id', sa.UUID(), nullable=False),
    sa.Column('reward_program_code', sa.String(), nullable=False),
    sa.Column('reward_accrual_type', sa.Enum('POINTS', 'CASHBACK', 'MILES', name='rewardaccrualtype', native_enum=False), nullable=True),
    sa.Column('reward_earn_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('reward_expiry_policy', sa.Enum('NO_EXPIRY', 'ONE_YEAR', 'TWO_YEARS', 'THREE_YEARS', name='rewardexpirypolicy', native_enum=False), nullable=True),
    sa.Column('reward_redemption_modes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('merchant_category_bonus', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['card_product_id'], ['card_product_core.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_product_id')
    )
    op.create_table('card_transaction_controls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_product_id', sa.UUID(), nullable=False),
    sa.Column('pos_enabled', sa.Boolean(), nullable=True),
    sa.Column('ecommerce_enabled', sa.Boolean(), nullable=True),
    sa.Column('atm_enabled', sa.Boolean(), nullable=True),
    sa.Column('contactless_enabled', sa.Boolean(), nullable=True),
    sa.Column('tokenization_supported', sa.Boolean(), nullable=True),
    sa.Column('recurring_txn_allowed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['card_product_id'], ['card_product_core.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_product_id')
    )
    op.create_table('card_usage_limits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_product_id', sa.UUID(), nullable=False),
    sa.Column('cash_advance_limit_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('international_txn_daily_cap', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('domestic_txn_daily_cap', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('contactless_txn_cap', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('max_txn_per_day', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_product_id'], ['card_product_core.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_product_id')
    )
    op.create_table('credit_account',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cif_id', sa.UUID(), nullable=False),
    sa.Column('credit_product_id', sa.UUID(), nullable=False),
    sa.Column('account_currency', sa.String(), nullable=True),
    sa.Column('sanctioned_limit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('available_limit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('outstanding_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('account_status', sa.Enum('ACTIVE', 'BLOCKED', 'CLOSED', name='accountstatus', native_enum=False), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cif_id'], ['customer_profiles.id'], ),
    sa.ForeignKeyConstraint(['credit_product_id'], ['credit_product_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_card_application',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cif_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('credit_product_id', sa.UUID(), nullable=False),
    sa.Column('card_product_id', sa.UUID(), nullable=False),
    sa.Column('application_status', sa.Enum('SUBMITTED', 'PENDING', 'APPROVED', 'REJECTED', name='applicationstatus', native_enum=False), nullable=True),
    sa.Column('current_stage', sa.Enum('KYC', 'DOCUMENTS', 'BUREAU', 'UNDERWRITING', 'FINAL', name='applicationstage', native_enum=False), nullable=True),
    sa.Column('employment_status', sa.String(), nullable=True),
    sa.Column('declared_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cibil_score', sa.Integer(), nullable=True),
    sa.Column('risk_band', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('cooling_period_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason_code', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['card_product_id'], ['card_product_core.id'], ),
    sa.ForeignKeyConstraint(['cif_id'], ['customer_profiles.id'], ),
    sa.ForeignKeyConstraint(['credit_product_id'], ['credit_product_information.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('credit_account_id', sa.UUID(), nullable=False),
    sa.Column('card_type', sa.Enum('PRIMARY', 'ADDON', 'VIRTUAL', name='cardtype', native_enum=False), nullable=True),
    sa.Column('pan_encrypted', sa.String(), nullable=False),
    sa.Column('pan_masked', sa.String(), nullable=False),
    sa.Column('expiry_date', sa.String(), nullable=False),
    sa.Column('card_status', sa.Enum('ACTIVE', 'BLOCKED', 'EXPIRED', name='cardstatus', native_enum=False), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['credit_account_id'], ['credit_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    op.drop_table('credit_card_application')
    op.drop_table('credit_account')
    op.drop_table('card_usage_limits')
    op.drop_table('card_transaction_controls')
    op.drop_table('card_rewards_configuration')
    op.drop_table('card_product_governance')
    op.drop_table('card_lifecycle_rules')
    op.drop_table('card_fraud_risk_profile')
    op.drop_table('card_billing_configuration')
    op.drop_table('card_authorization_rules')
    op.drop_table('credit_product_limits')
    op.drop_table('credit_product_international_config')
    op.drop_table('credit_product_interest_framework')
    op.drop_table('credit_product_governance')
    op.drop_table('credit_product_fees')
    op.drop_table('credit_product_eligibility_rules')
    op.drop_table('credit_product_compliance_metadata')
    op.drop_table('credit_product_accounting_mapping')
    op.drop_table('card_product_core')
    op.drop_index(op.f('ix_credit_product_information_product_code'), table_name='credit_product_information')
    op.drop_table('credit_product_information')
    # ### end Alembic commands ###
