"""Update admin model for full name and contact details

Revision ID: 1c2c2204432e
Revises: 9d4ee9b05f9e
Create Date: 2026-03-03 11:19:20.373857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c2c2204432e'
down_revision: Union[str, Sequence[str], None] = '9d4ee9b05f9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('first_name', sa.String(length=100), server_default='System', nullable=False))
    op.add_column('admins', sa.Column('middle_name', sa.String(length=100), nullable=True))
    op.add_column('admins', sa.Column('last_name', sa.String(length=100), server_default='Admin', nullable=False))
    op.add_column('admins', sa.Column('suffix', sa.Enum('JR', 'SR', 'II', 'III', name='suffix', native_enum=False), nullable=True))
    op.add_column('admins', sa.Column('country_code', sa.String(length=10), nullable=True))
    op.add_column('admins', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.drop_constraint(op.f('admins_contact_key'), 'admins', type_='unique')
    op.drop_column('admins', 'contact')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('contact', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('admins_contact_key'), 'admins', ['contact'], postgresql_nulls_not_distinct=False)
    op.drop_column('admins', 'phone_number')
    op.drop_column('admins', 'country_code')
    op.drop_column('admins', 'suffix')
    op.drop_column('admins', 'last_name')
    op.drop_column('admins', 'middle_name')
    op.drop_column('admins', 'first_name')
    # ### end Alembic commands ###
