"""Add CCM tables take 2

Revision ID: c3f60a962ee3
Revises: 7470220b5aa4
Create Date: 2026-03-13 10:41:42.222780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3f60a962ee3'
down_revision: Union[str, Sequence[str], None] = '7470220b5aa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ccm_credit_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('card_number', sa.String(), nullable=False),
    sa.Column('card_network', sa.Enum('VISA', 'MASTERCARD', 'RUPAY', 'AMEX', name='cardnetwork', native_enum=False), nullable=False),
    sa.Column('card_variant', sa.Enum('CLASSIC', 'GOLD', 'PLATINUM', 'SIGNATURE', 'INFINITE', name='cardvariant', native_enum=False), nullable=False),
    sa.Column('expiry_date', sa.String(), nullable=False),
    sa.Column('cvv_hash', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'ISSUED', 'INACTIVE', 'ACTIVE', 'BLOCKED_USER', 'BLOCKED_FRAUD', 'BLOCKED_TEMP', 'EXPIRED', 'TERMINATED', 'REPLACED', name='ccmcardstatus', native_enum=False), nullable=True),
    sa.Column('is_virtual', sa.Boolean(), nullable=True),
    sa.Column('is_contactless_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_international_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_online_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_atm_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_domestic_enabled', sa.Boolean(), nullable=True),
    sa.Column('daily_spend_limit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('daily_withdraw_limit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blocked_reason', sa.Enum('GEO_MISMATCH', 'HIGH_VELOCITY', 'MERCHANT_BLACKLIST', 'AMOUNT_LIMIT_EXCEEDED', 'UNUSUAL_TIME', 'FRAUD', name='ccmfraudblockreason', native_enum=False), nullable=True),
    sa.Column('reissue_reference', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reissue_reference'], ['ccm_credit_cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ccm_credit_cards_card_number'), 'ccm_credit_cards', ['card_number'], unique=True)
    op.create_table('ccm_credit_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('available_credit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('outstanding_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cash_limit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('billing_cycle_day', sa.Integer(), nullable=True),
    sa.Column('minimum_due', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('late_fee', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_statement_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['ccm_credit_cards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id')
    )
    op.create_table('ccm_card_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('credit_account_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('merchant_name', sa.String(), nullable=False),
    sa.Column('merchant_category', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('transaction_type', sa.Enum('PURCHASE', 'REFUND', 'FEE', 'INTEREST', 'PAYMENT', 'REVERSAL', name='ccmtransactiontype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REVERSED', name='ccmtransactionstatus', native_enum=False), nullable=True),
    sa.Column('geo_location', sa.String(), nullable=True),
    sa.Column('is_fraud_flagged', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['ccm_credit_cards.id'], ),
    sa.ForeignKeyConstraint(['credit_account_id'], ['ccm_credit_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ccm_card_transactions')
    op.drop_table('ccm_credit_accounts')
    op.drop_index(op.f('ix_ccm_credit_cards_card_number'), table_name='ccm_credit_cards')
    op.drop_table('ccm_credit_cards')
    # ### end Alembic commands ###
