"""Add kyc_reupload_requested

Revision ID: dbb233b24855
Revises: e2cbd3aa6dbf
Create Date: 2026-02-27 16:59:29.964277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbb233b24855'
down_revision: Union[str, Sequence[str], None] = 'e2cbd3aa6dbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_profiles', sa.Column('kyc_reupload_requested', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_profiles', 'kyc_reupload_requested')
    # ### end Alembic commands ###
