"""Update employment fields

Revision ID: e2cbd3aa6dbf
Revises: eb362f80130a
Create Date: 2026-02-27 14:42:55.411639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2cbd3aa6dbf'
down_revision: Union[str, Sequence[str], None] = 'eb362f80130a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employment_details', sa.Column('organisation_name', sa.String(), nullable=True))
    op.add_column('employment_details', sa.Column('organisation_country', sa.String(), nullable=True))
    op.add_column('employment_details', sa.Column('designation', sa.String(), nullable=True))
    op.drop_column('employment_details', 'job_title')
    op.drop_column('employment_details', 'employer_name')
    op.drop_column('employment_details', 'employer_country')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employment_details', sa.Column('employer_country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employment_details', sa.Column('employer_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employment_details', sa.Column('job_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('employment_details', 'designation')
    op.drop_column('employment_details', 'organisation_country')
    op.drop_column('employment_details', 'organisation_name')
    # ### end Alembic commands ###
