"""CIF Phase 1 Clean

Revision ID: eb362f80130a
Revises: 1c77d11e2046
Create Date: 2026-02-26 18:02:32.089292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb362f80130a'
down_revision: Union[str, Sequence[str], None] = '1c77d11e2046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fatca_declarations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_profile_id', sa.UUID(), nullable=True),
    sa.Column('us_citizen', sa.Boolean(), nullable=True),
    sa.Column('us_tax_resident', sa.Boolean(), nullable=True),
    sa.Column('us_tin', sa.String(), nullable=True),
    sa.Column('declaration_signed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_profile_id'], ['customer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_profile_id')
    )
    op.add_column('customer_profiles', sa.Column('cif_number', sa.String(), nullable=True))
    op.add_column('customer_profiles', sa.Column('customer_status', sa.String(), nullable=True))
    op.add_column('customer_profiles', sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customer_profiles', sa.Column('terms_ip_address', sa.String(), nullable=True))
    op.add_column('customer_profiles', sa.Column('terms_user_agent', sa.String(), nullable=True))
    op.add_column('customer_profiles', sa.Column('pep_flag', sa.Boolean(), nullable=True))
    op.add_column('customer_profiles', sa.Column('high_risk_flag', sa.Boolean(), nullable=True))
    op.add_column('customer_profiles', sa.Column('fatca_required', sa.Boolean(), nullable=True))
    op.alter_column('customer_profiles', 'country_of_residence',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('INDIA', 'USA', 'UK', 'CANADA', 'AUSTRALIA', 'UAE', name='country', native_enum=False),
               existing_nullable=True)
    op.alter_column('customer_profiles', 'nationality',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('INDIA', 'USA', 'UK', 'CANADA', 'AUSTRALIA', 'UAE', name='country', native_enum=False),
               existing_nullable=True)
    op.alter_column('customer_profiles', 'dual_citizenship',
               existing_type=sa.BOOLEAN(),
               type_=sa.Enum('YES', 'NO', name='yesno', native_enum=False),
               existing_nullable=True)
    op.alter_column('customer_profiles', 'kyc_status',
               existing_type=postgresql.ENUM('INCOMPLETE', 'PENDING', 'VERIFIED', 'REJECTED', name='kycstatus'),
               type_=sa.Enum('INCOMPLETE', 'PENDING', 'VERIFIED', 'REJECTED', name='kycstatus', native_enum=False),
               existing_nullable=True)
    op.create_index(op.f('ix_customer_profiles_cif_number'), 'customer_profiles', ['cif_number'], unique=True)
    op.alter_column('employment_details', 'employment_type',
               existing_type=postgresql.ENUM('SALARIED', 'SELF_EMPLOYED', 'STUDENT', 'RETIRED', 'UNEMPLOYED', name='employmenttype'),
               type_=sa.Enum('FULL_TIME', 'PART_TIME', 'SELF_EMPLOYED', 'CONTRACTOR', 'STUDENT', 'RETIRED', 'UNEMPLOYED', name='employmenttype', native_enum=False),
               existing_nullable=True)
    op.alter_column('otp_codes', 'purpose',
               existing_type=postgresql.ENUM('LOGIN', 'REGISTRATION', 'PASSWORD_RESET', name='otppurpose'),
               type_=sa.Enum('LOGIN', 'REGISTRATION', 'PASSWORD_RESET', name='otppurpose', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('otp_codes', 'purpose',
               existing_type=sa.Enum('LOGIN', 'REGISTRATION', 'PASSWORD_RESET', name='otppurpose', native_enum=False),
               type_=postgresql.ENUM('LOGIN', 'REGISTRATION', 'PASSWORD_RESET', name='otppurpose'),
               existing_nullable=False)
    op.alter_column('employment_details', 'employment_type',
               existing_type=sa.Enum('FULL_TIME', 'PART_TIME', 'SELF_EMPLOYED', 'CONTRACTOR', 'STUDENT', 'RETIRED', 'UNEMPLOYED', name='employmenttype', native_enum=False),
               type_=postgresql.ENUM('SALARIED', 'SELF_EMPLOYED', 'STUDENT', 'RETIRED', 'UNEMPLOYED', name='employmenttype'),
               existing_nullable=True)
    op.drop_index(op.f('ix_customer_profiles_cif_number'), table_name='customer_profiles')
    op.alter_column('customer_profiles', 'kyc_status',
               existing_type=sa.Enum('INCOMPLETE', 'PENDING', 'VERIFIED', 'REJECTED', name='kycstatus', native_enum=False),
               type_=postgresql.ENUM('INCOMPLETE', 'PENDING', 'VERIFIED', 'REJECTED', name='kycstatus'),
               existing_nullable=True)
    op.alter_column('customer_profiles', 'dual_citizenship',
               existing_type=sa.Enum('YES', 'NO', name='yesno', native_enum=False),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('customer_profiles', 'nationality',
               existing_type=sa.Enum('INDIA', 'USA', 'UK', 'CANADA', 'AUSTRALIA', 'UAE', name='country', native_enum=False),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('customer_profiles', 'country_of_residence',
               existing_type=sa.Enum('INDIA', 'USA', 'UK', 'CANADA', 'AUSTRALIA', 'UAE', name='country', native_enum=False),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('customer_profiles', 'fatca_required')
    op.drop_column('customer_profiles', 'high_risk_flag')
    op.drop_column('customer_profiles', 'pep_flag')
    op.drop_column('customer_profiles', 'terms_user_agent')
    op.drop_column('customer_profiles', 'terms_ip_address')
    op.drop_column('customer_profiles', 'terms_accepted_at')
    op.drop_column('customer_profiles', 'customer_status')
    op.drop_column('customer_profiles', 'cif_number')
    op.drop_table('fatca_declarations')
    # ### end Alembic commands ###
